### ISSUE TITLE
reportbutton: Add inactivity logout count down timer together with logged in time

### ISSUE THREAD

**Issue by permedd** [open-osrs/runelite#1116]
**Additional context**

![](https://user-images.githubusercontent.com/37475765/37556034-437b81b4-29e8-11e8-8a73-ee4121d4dfb4.png)

This is the normal report player section looks for me but I want it so I can see my 5:00 minute inactivity logout time as well so like this.

![](https://user-images.githubusercontent.com/37475765/37556052-71a27282-29e8-11e8-98d2-01d1b3da6390.png)

This is just a template on how I want it to look like.

![](https://user-images.githubusercontent.com/37475765/37556077-9bbf39c4-29e8-11e8-8cf7-c69e1658ee3a.png)

And this is how I want it to look like at the end.

This will be useful instead of having idle notification we can have a timer on the report player section, I think this will bring more people to use this client cos no other clients have these two together, like me i don't like using idle notification i rather see a timer.

Side note 
i think the inactivity timer is 20minutes so make it so that it starts from 20minutes and counts down.

**Comment by pklite** [comment]
i think the inactivity timer is only 20 minutes if you're currently in combat. if you aren't doing anything at all i think its 5 mins?

**Comment by permedd** [comment]
Ah ok then maybe we can separate then by colour?
Yellow - is under attack (which will be a 20 minutes count down)
Green - is not under attack (which will be a 5 minutes count down)

**Comment by permedd** [comment]
maybe another suggestion for this is maybe you can do it like this
time online [how long left to logout]
**01:33:08 [00:04:59]**
I have added this because maybe 
![image](https://user-images.githubusercontent.com/37475765/61962265-0d685100-afc1-11e9-84e6-79a2d8941dc3.png) 
having might make the numbers be super small.




this is the new updated version which you might consider to add is this
![image](https://user-images.githubusercontent.com/37475765/61962820-5240b780-afc2-11e9-858a-3a3b3e63b075.png)
like i said before
Yellow - is under attack (which will be a 20 minutes count down)

![image](https://user-images.githubusercontent.com/37475765/61962862-671d4b00-afc2-11e9-9996-2d91f704dd77.png)
like i said before
Green - is not under attack (which will be a 5 minutes count down)
