### ISSUE TITLE
grounditems: menu re-ordering/grouping conflicts

### ISSUE THREAD

**Issue by SRLJustin** [open-osrs/runelite#1118]
Not exactly sure what is triggering this issue with item grouping but the rightclick menu options rapidly change (it's a lot slower in the gif than in-game)

https://i.imgur.com/0lArUUW.gifv
https://i.imgur.com/nxZdZ29.gifv

Item Grouping off then back on:
https://imgur.com/gTqvH5L

Here is a copy of my grounditems config:

https://drive.google.com/file/d/1xT2B5DcC0TEcIyKJtCWmtSnkcQYlr5MB/view

I was having this issue when maven was still active and also with gradle build

cc @Kyleeld

**Comment by Ganom** [comment]
This is occurring with the ground items plugin rather than MES yeah?

**Comment by SRLJustin** [comment]
Correct, I didn't realize I put MES

**Comment by Kyleeld** [comment]
does this happen for certain items, or items grouped over a certain value?

i still cannot replicate.

**Comment by SRLJustin** [comment]
it looks to happen when the loot pile has an untradeable item or something with a high value in it
