### ISSUE TITLE
time left

### ISSUE THREAD

**Issue by permedd** [open-osrs/runelite#1153]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
- when ever there 'days' appears on the xp orb at the timeleft, it goes to a separate line what i mean is lets say it says 12Day, 13:10:03 the '13:10:03' numbers will not stay on the same line as the Day number it goes to a separate line.
it shows this
Timeleft 12 days
                13:10:03

when it should be showing this
timeleft: 12Days, 13:10:03
it should be on one line not going to a separate line it just makes the box much bigger which is kinda annoying.

**To Reproduce**
Steps to reproduce the behaviour:
- hoover your mouse on to the xp orb, it will say time left.

**Expected behaviour**
- at the time left it should all be on one line.

**Screenshots**
![image](https://user-images.githubusercontent.com/37475765/61997926-63f88c80-b0a0-11e9-9609-7c73aeaf2227.png)

![image](https://user-images.githubusercontent.com/37475765/61997906-3c092900-b0a0-11e9-9f3a-12f9aaf485e2.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - LATEST VERSION

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Kyleeld** [comment]
It’s fine as is, having it on one line makes the rest of it messy and ugly

**Comment by Lucwousin** [comment]
but... Being able to view it in hours:minutes:seconds should be an option in my opinion. Better than days, as you don't wanna know how many 24 hours straight you're gonna have to do that

**Comment by permedd** [comment]
I do agree with what you said @lucwousin and it will then be on one line.
