### ISSUE TITLE
task info box

### ISSUE THREAD

**Issue by permedd** [open-osrs/runelite#1184]
**Describe the bug**
- when i kill a npc the kill count does not go down, it was working after the 2.1.1.0 update but it stopped working after a while.

**To Reproduce**
1. task infobox

**Expected behavior**
- it should go down automatically without me having to keep turning keep checking how many kills left by enchanted gem or slayer helm etc

**Screenshots**
https://i.gyazo.com/67cf8289a1870d81fb6362ceab9e6b5d.mp4
- this gyazo shows that i had 45 npcs to kill but when i killed 3 it did not go down till i re-checked how many kills left then it switched to 42 kills left

- 
- 
- 
![image](https://user-images.githubusercontent.com/37475765/62046877-eef09880-b200-11e9-99e8-96cd3a77abb2.png)
- this is proof of the info box activated on the runelite client.

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
- latest version

**Comment by xKylee** [comment]
can you confirm if this is still an issue in 2.1.4.0?

**Comment by permedd** [comment]
I think this is fixed @xky

**Comment by permedd** [comment]
this is still bugged and it got worse, whenever you re-open the launcher it shows different task info, till you have to right-click 'check' the gem.
and whenever you re-log, it shows the slayer task you are on but the count down is wrong.
