### ISSUE TITLE
required items for slayer tasks

### ISSUE THREAD

**Issue by permedd** [open-osrs/runelite#1185]
**Additional context**
- there should be a text box similar to the clue scroll where it says 'Requires Spade!' the picture below will show what i mean.
![image](https://user-images.githubusercontent.com/37475765/62047318-172cc700-b202-11e9-806f-c8979c0f8c39.png)
-
-
- but with this let's say you have a gargoyle task it should say 'Required Hammer!' and till you get the hammer it will stay there if the player does not get a hammer it will stay there.
this should also happen to npcs such as rockslugs where they need salt to be killed, so let's say you got a task and you have to kill 145 rock slugs it will then say; Required Salt! 0/145, this means that they will need to get 145 salts, just in case they forget how many they have, and once they have the 145 salts, the textbox will disappear.

- this suggestion should happen to every NPCs that has a weakness or a required item

**Comment by Judaxx** [comment]
Should this apply for the wearable required items too? Like the witchwood icon for cave horrors, nose peg/slayer helm for abby specters, etc?

I can pick this one up if nobody is doing it yet.

**Comment by xKylee** [comment]
i would say so if the task requires it :) and we wont get round to it yet so feel free :)

**Comment by permedd** [comment]
https://github.com/runelite-extended/runelite/issues/1185#issuecomment-523593321

Yes please.
