### ISSUE TITLE
slayer monster weakness

### ISSUE THREAD

**Issue by permedd** [open-osrs/runelite#1186]
**Describe the bug**
- i got the slayer monster weakness activated but it does not show the weakness on top of the monsters

**Expected behavior**
- it should show the weakness of the monsters when they are about to be finished off.

**Screenshots**
https://i.gyazo.com/a7f8ca2e5e417e0aa07ebb92e56bdb48.mp4 
- i got a gif i hope that's okay, in this gif it shows that it does not show the monster's weakness when it was just about to die.

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - latest version

**Comment by xKylee** [comment]
can you confirm if this is still an issue in 2.1.4.0?

**Comment by permedd** [comment]
yes, right now i got banshee task and it did not tell me that i needed a earmuffs to kill the npc, i think it doesn't work for any npcs @xKylee

**Comment by permedd** [comment]
Yes still a bug. @xkylee
