### ISSUE TITLE
Olm head turner tick timer

### ISSUE THREAD

**Issue by JackSparrow43** [open-osrs/runelite#1187]
Tick timer for when olm turns head - 1 being the tick it turns its head. good for people learning how to solo :)

**Comment by sunha7** [comment]
This is already a thing in the CoX helper plugin

**Comment by JackSparrow43** [comment]
I meant for the olm head turning, not its attacks.

**Comment by farhan1666** [comment]
in solos his head will turn at the same time he does an action so having a separate timer or even mentioning that the head will turn in the current timer is pretty useless imo, I'd only see this being useful in team raids if someone was trying to run the head, but speaking from experience its much easier to just wait for the head to turn

**Comment by JackSparrow43** [comment]
Don't you have to move the same tick as the head turns, if u wait for the head to turn and then click, won't u always get it? This addition would probably only take like 10-15 minutes to add, I think.
