### ISSUE TITLE
Slayer tracker not working

### ISSUE THREAD

**Issue by Lucifirius** [open-osrs/runelite#1196]
https://i.vgy.me/DftAzP.png

Nothing slayer related is being tracked except this, when the game updates for every 10 kills. https://i.vgy.me/CLpdM1.png

**Comment by Hermetism** [comment]
Removing the API fixes this and the counter not updating except for when you check with a gem etc.

example [here](https://github.com/Hermetism/RUNELIGHT/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java)

**Comment by Kyleeld** [comment]
what is it with you and removing api shit

**Comment by xKylee** [comment]
can you confirm if this is still an issue in 2.1.4.0?
