### ISSUE TITLE
DC Scout Notifier

### ISSUE THREAD

**Issue by ThatGamerBlue** [open-osrs/runelite#1252]
Add an infobox on screen when a raid can be disconnect scouted

Currently known layouts: SCPFCCSPCF, CSPFCCCSSF, SCFPCSCPCF, PCSFCPCSCF, SCCFCPSCSF, SCPFCCCSSF, SCPFCPCSCF (courtesy of Maxed Sensei#0699)

**Comment by SRLJustin** [comment]
#1308 will closes this
