### ISSUE TITLE
MES broken swaps

### ISSUE THREAD

**Issue by Owain94** [open-osrs/runelite#1376]
@Ganom 

* ~~Pure ess are drop only~~ - Non issue 
* ~~Mouse keys still don't register~~ - Won’t fix 
* Empty trap first option is not reset (trap with a caught chin works)

**Comment by Jommos** [comment]
Mythic Cape plugin doesn't work.
Teleports instead of removing even though when you hover over rack it says remove

**Comment by Ganom** [comment]
> 
> 
> Mythic Cape plugin doesn't work.
> Teleports instead of removing even though when you hover over rack it says remove

Unable to reproduce, did 10 minutes of myth cape without the issue you are describing.

**Comment by Ganom** [comment]
>     * Pure ess are drop only
>     * Mouse keys still don't register
>     * Empty trap first option is not reset (trap with a caught chin works)

1st is from runecraft plugin.
2nd is a wont-fix issue, as that is core menu manager functionality, where only valid clicks are used to rebuild menus.
3rd, will fix soon. ty

**Comment by xKylee** [comment]
Describe the bug
used custom swap on torfinn so its set to collect instead of travel, it is not swapping.

Expected behavior
expecting ti to swap travel with collect so left click is collect

Screenshots
https://imgur.com/pHHBuDs

**Comment by Ganom** [comment]
> 
> 
> Describe the bug
> used custom swap on torfinn so its set to collect instead of travel, it is not swapping.
> 
> Expected behavior
> expecting ti to swap travel with collect so left click is collect
> 
> Screenshots
> https://imgur.com/pHHBuDs

Swaps are overwritten by priority entries, no custom swap can overwrite priority entries.

**Comment by Jackyfalyfe** [comment]
A wide number of my potions (e.g antifire (3), stamina (1)s) are being shown as deposit/withdraw all by default even when choosing to select one. No custom menu entry written explicitly for them

**Comment by Ganom** [comment]
> 
> 
> A wide number of my potions (e.g antifire (3), stamina (1)s) are being shown as deposit/withdraw all by default even when choosing to select one. No custom menu entry written explicitly for them

Bank swaps are no longer strict, so that means stamina potion will do all stamina potions, while stamina potion(4) will do just stamina potion.

**Comment by Jackyfalyfe** [comment]
Default left click for all items becomes "use" regardless of item type. Resetting client fixes it.

**Comment by Crystalknoct** [comment]
Has this produced an error or do you have logs when when its happened?

**Comment by Jur0u** [comment]
> Default left click for all items becomes "use" regardless of item type. Resetting client fixes it.

After 20-30 mins in-game everything becomes "drop" for me. 

![image](https://user-images.githubusercontent.com/42985735/63227529-38ebef00-c1ad-11e9-859c-fb1423aabf14.png)

**Comment by Ganom** [comment]
> 
> 
> > Default left click for all items becomes "use" regardless of item type. Resetting client fixes it.
> 
> After 20-30 mins in-game everything becomes "drop" for me.
> 
> ![image](https://user-images.githubusercontent.com/42985735/63227529-38ebef00-c1ad-11e9-859c-fb1423aabf14.png)

Thats shift click customization breaking.

**Comment by se7enAte9** [comment]
> 2nd is a wont-fix issue, as that is core menu manager functionality, where only valid clicks are used to rebuild menus.

For anyone that is experiencing that issue: AHK or any other key manager where you able to send the up/down keys individually should work. 

For anyone curious about why that issue occurs: it is being caused by a workaround I put in place because menu entries for draggable widgets are handled differently than normal menu entries. The reason both WMK and the click function in AHK are affected is that they do not have any delay between up/down and the workaround depends on the delay between up/down that normally occurs when left clicking. I was not sure of a better solution that wouldn't adversely affect performance when I added the workaround in and haven't been able to look at it since then.

**Comment by GalaxyKindred** [comment]
custom swap for torfinn to switch from travel to collection left click is not working was working before what ever update broke the entry swappers 
![image](https://user-images.githubusercontent.com/52353077/63267214-8aed4d00-c25f-11e9-8253-0b8cd78e42ff.png)

**Comment by Vikings09876** [comment]
Another issue with MES is for items with just the word bone in it, it's swapping the item to USE. IE: Bone bolts are swapped to use instead of wield just because they have the word bone in them.

**Comment by Crystalknoct** [comment]
For vikings issue wouldnt this also affect things like bone sack, dagger, etc?
