### ISSUE TITLE
LootTracker website

### ISSUE THREAD

**Issue by kulershk** [open-osrs/runelite#1378]
A while ago I brought up the topic about Loot Tracker website in discord people were interested but nothing happened and forgot about it.

So now I'm writing here to be clear if you would be willing to add something like this to rl+

Project is already open-source and available on GitHub (kulershk/LootTracker)

Here are some screenshots of the page
https://prnt.sc/otxhty
https://prnt.sc/otxiqh
https://prnt.sc/otxiw9
https://prnt.sc/otxj2p

Let me know guys what you think.

Cheers

**Comment by f0rmatme** [comment]
i can host it on the runeliteplus domain but someone will have to update the loottracker plugin to make api calls.

Would be better to move away from runelites
