### ISSUE TITLE
Boss tick timers for hydra, maiden, vorkath

### ISSUE THREAD

**Issue by ady19980** [open-osrs/runelite#1405]
In the Boss tick timers plugin, it would be cool if it had a maiden tick timer which could be helpful for solos, hydra(hydra tick timers already exist for mini-hydras but not for alchemical) and vorkath for easier prayer flicking.

Might've missed some other useful bosses that's all I can think of in addition to gwd and dks which already exist in the plugin

**Comment by Lucwousin** [comment]
I'll do hydra, also poison plugin and any other plugin i mightvd done

**Comment by ady19980** [comment]
> I'll do hydra, also poison plugin and any other plugin i mightvd done

For hydra, during the blue phase, there is also an AOE, the tile of the lightening projectile's destination could be highlighted a couple of seconds before it hits you (when the projectile is fired)
