### ISSUE TITLE
Menu swapping priority argument update removes flexibility

### ISSUE THREAD

**Issue by ady19980** [open-osrs/runelite#1426]
With the recent update to custom menu entry swapping, you can't have swaps for specific options, but only for specific items/npcs/objects.

For example the old menu entry swap:
Remove, Blessing4 : Mount Kaarulm, Blessing4

new menu entry swap:
Mount Kaarulm, Blessing4: 0

So it edits the mount kaarulm teleport as option 1 in inventory as well as equipment inventory, even if you only want it to exist for equipment inventory.

**Comment by Lucwousin** [comment]
While this is a fair point, you could add `equip`, and make it have a higher priority than your other one
