### ISSUE TITLE
Entity Hiding Based on Animation ID

### ISSUE THREAD

**Issue by lulwut** [open-osrs/runelite#1458]
To quote some dude in discord 

> Also, McNiel has a really customizable entity hider that makes for some interesting uses, especially hiding npcs based on what animation code they're performing
allows you to entity hide npcs performing their death animation
really useful for high level pvm

**Comment by lulwut** [comment]
@gamon

**Comment by xKylee** [comment]
No, it’s for npc’s only

**Comment by jjfishbeck44** [comment]
Someone add in the feature to be able to hide every one/thing that isn’t interacting with your own player? This would NOT include people following you. 
^ need this for big wilderness wars that sometimes get pushed into single combat and you need to find who’s attacking you.
