### ISSUE TITLE
Menu Entry Swapper Not Working In Trade Window

### ISSUE THREAD

**Issue by Conor092** [open-osrs/runelite#1462]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
For Custom menu entry swaps, trying to change anything to do with offering in the trade screen doesn't seem to work, you can remove-all etc. but offering can't be changed.

** list of commands tried **
Offer-All, Death rune:0 
Offer-All, Death rune:100
Offer-all, Death rune:0
Offer-10, Death rune:0

None of the above works

**To Reproduce**
1. Add the following line into the custom commands section of the menu entry swapper Offer-all, Death rune:0

2. Trade another individual and try and trade over all of the selected rune
3. Only offering one at a time instead of all

**Expected behavior**
Its suppose to trade over all of the death runes on a single click

**Screenshots**
http://prntscr.com/oy64fv

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: Lastest up to date
 - Launcher version: No idea

**Additional context**

**Comment by Lucwousin** [comment]
First off, all the `offer all` methods would end up being the same one, like literally, collided down into 1. Not sure why it's not working though

**Comment by Conor092** [comment]
I was just showing you all the different ways I tired to get it to work, I didn't use them all at the same time.
