### ISSUE TITLE
Pressing right alt disables my anti drag even though that is not my hotkey.

### ISSUE THREAD

**Issue by farhan1666** [open-osrs/runelite#1468]
This is probably only annoying to me as right alt is my push to toggle mute button on discord but it is a bug nonetheless. This does not happen when I press left alt and my hotkey is ctrl (both ctrls work for this). This does not happen when my anti drag hotkey is not ctrl. Pressing right alt only disables the anti drag and does not turn it back on.
My config: https://i.imgur.com/607z8qt.png

**Comment by ThatGamerBlue** [comment]
Do you have any hotkeys set to ralt in any other plugins?

**Comment by farhan1666** [comment]
No

**Comment by xKylee** [comment]
i cannot replicate this in latest master.

**Comment by pklite** [comment]
![image](https://user-images.githubusercontent.com/46624825/64307963-bfeae680-cf65-11e9-9093-4ae7922e3b56.png)
