### ISSUE TITLE
Add total gear value to Player Scouter

### ISSUE THREAD

**Issue by RaidanAlyssi** [open-osrs/runelite#1488]
It would be great if we could select a minimum total gear value for scouter.
So it would ignore no skull or item prot.

**Comment by xKylee** [comment]
You can....

**Comment by RaidanAlyssi** [comment]
Where? All I see is minimum risk which doesn't include protected items, and minimum value which is for which items are listed on scouts.

**Comment by Ganom** [comment]
Yeah, this is a valid feature request @xKylee
