### ISSUE TITLE
Blackjack: Menu entry swapping issues

### ISSUE THREAD

**Issue by lordzuku** [open-osrs/runelite#1490]
when blackjacking the menu entry swapper doesnt revert back to knock-out fast enough, if you are spam clicking the thugs occasionally it will try to pickpocket the bandit while its not knocked out
slowing down the xp/hr significantly

https://gyazo.com/b763d22af96fb901cc563f771685b322 video of it happening

also if you disable the plugin while blackjacking it will require rebooting the client, as it will have the leftclick stuck on knockout even after reenabling

**Comment by lordzuku** [comment]
https://gyazo.com/b6ae5bebf430639596b0044b5af2e742 that gif didnt do a great job at showing it, here is a better one

the animation of me reaching forward for the thug is the bad pickpocket that shouldnt happen

**Comment by 07RS** [comment]
Just looks like you are lagging and don't initiate the first pickpocket fast enough. The second pickpocket should occur because you are always supposed to steal from him twice per knockout
