### ISSUE TITLE
Player Indicators Preferences Not Saving

### ISSUE THREAD

**Issue by jonnymichaelson** [open-osrs/runelite#1497]
**Describe the bug**
When I go into the Player Indicators plugin and change my Pile Indication Methods in the Caller Targets and Friends section, the new preference does not save. 

**To Reproduce**
1. Go to 'Player Indicators'
2. Click on any new pile indication method in the Caller Targets section
3. Go back to the main plugin menu
4. Then go back into Player Indicators and look at the indication method in the caller target section, it will not have saved and will be the default "Above Head" method.

**Expected behavior**
I expected it to save my new indication preference.

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: 1.5.33-SNAPSHOT
 - Launcher version: 2.1.5.0 is my RuneLitePlus version

**Additional context**
I'll provide additional context upon request, since I don't know what would help. This problem may be restricted to macOS, I'm not sure though.

**Additional Issue**: The color I set for Caller Target does not override the color of Attackable Players I have set. It should override all other colors.

**Comment by pklite** [comment]
This is possibly related to/fixed in #1540 but needs to be tested to confirm
