### ISSUE TITLE
Player Indicators: Clan ranks not showing next to names above head or in menu

### ISSUE THREAD

**Issue by farhan1666** [open-osrs/runelite#1510]

**Comment by Lucwousin** [comment]
Any additional info? This is the first time I've heard of this

**Comment by SRLJustin** [comment]
With Player Indicators, you could enable 'Clan Ranks' to show next to the players name (if you had it enabled)

Picture:
![Corporeal Beast(56)](https://user-images.githubusercontent.com/1625140/64140754-e404d580-ce48-11e9-8cad-5730098faaa3.png)

This is no longer possible with the current plugin

**Comment by SRLJustin** [comment]
@Lucwousin do you require any further information?

**Comment by pklite** [comment]
this is getting re-added in #1556

**Comment by SRLJustin** [comment]
clan ranks do not show if they are also on your friends list, also the position is very weird

**Comment by stone-wall** [comment]
was fixed in #1796
