### ISSUE TITLE
Buffer/MTU overflow (?)

### ISSUE THREAD

**Issue by Macweese** [open-osrs/runelite#1552]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Bug description:**
Bypass of chatmessages' character limit. RuneLite+ function copy paste messages into chat box, allows overriding the 80 character limit set by Jagex. Sending a string larger than the MTU causes an error; A 1-2 second disconnection.

Proposed fix:
Limit the string sent to a maximum of 80 characters, as the game won't send any more regardless.

Other uses:
This can be deliberately abused to bypass 6-hour log limit, e.g. inside Nightmare Zone - without logging out or hopping worlds. Allowing you to continue training in the same instanced session.
Perhaps as a 6-hour reset function.

**To Reproduce**
1. Copy any character to clipboard, depending on which character as data sizes vary.
2. Paste enough of them and you will eventually exceed the MTU, hit enter to send message.
3. See error.

**Expected behaviour**
Normal chat behaviour.

**Demonstration:**
https://www.youtube.com/watch?v=MHd-U1G3fnY

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.33
 - RuneLitePlus version: 2.1.5.0
 - Oldschool revision: Rev 182

**Additional context**
N/A

**Comment by ThatGamerBlue** [comment]
Can you post the message you sent over chat? Tried a message of length 104 and it didn't do anything.

**Comment by Macweese** [comment]
> Can you post the message you sent over chat? Tried a message of length 130 and it didn't do anything.

It depends entirely on the data size of the message, not which or the amount of characters. There is a sort of failsafe in place that only lets you send the first 80 characters even if the pasted message is longer, and is small enough to be processed. Each character is between 8-16 bits so generally, a message >250 chars should do the trick.

Try pasting the message over and over.

**Comment by ThatGamerBlue** [comment]
Got it to work with the message `abcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyzabcdefghijklmnopqrstuvqxyz`

Not sure how the pasting works but it should be fixable relatively easily.

**Comment by SRLJustin** [comment]
```java
2019-09-06 19:39:56 [Client] ERROR net.runelite.client.RuneLite - Game crash: 96 73 5008
java.lang.ArrayIndexOutOfBoundsException: 260
	at hr.s(hr.java:77)
	at il.s(il.java:55)
	at c.an(t.java:3039)
	at du.i(du.java:418)
	at client.copy$runScript(client.java:355)
	at v.j(v.java:135)
	at cc.s(cc.java:97)
	at client.fc(client.java:3139)
	at client.aj(client.java:1280)
	at bw.o(bw.java:365)
	at bw.run(bw.java:344)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Crystalknoct** [comment]
2019-09-06 03:39:22 [Client] ERROR net.runelite.client.RuneLite - Game crash: 96 73 5008
java.lang.ArrayIndexOutOfBoundsException: 260
	at hr.s(hr.java:81)
	at il.s(il.java:55)
	at c.an(t.java:3039)
	at du.i(du.java:418)
	at client.copy$runScript(client.java:355)
	at v.j(v.java:135)
	at cc.s(cc.java:97)
	at client.fc(client.java:3139)
	at client.aj(client.java:1280)
	at bw.o(bw.java:365)
	at bw.run(bw.java:344)
	at java.lang.Thread.run(Thread.java:748)

**Comment by SRLJustin** [comment]
> Idk how to make it pretty.
> 
> ```
> java.lang.ArrayIndexOutOfBoundsException: 260
> 	at hr.s(hr.java:81)
> 	at il.s(il.java:55)
> 	at c.an(t.java:3039)
> 	at du.i(du.java:418)
> 	at client.copy$runScript(client.java:355)
> 	at v.j(v.java:135)
> 	at cc.s(cc.java:97)
> 	at client.fc(client.java:3139)
> 	at client.aj(client.java:1280)
> 	at bw.o(bw.java:365)
> 	at bw.run(bw.java:344)
> 	at java.lang.Thread.run(Thread.java:748)```
> ```
![wfb40jv 1](https://user-images.githubusercontent.com/1625140/64418880-234c5400-d0df-11e9-8535-1f93e460e35b.png)
