### ISSUE TITLE
Menu Entry Swapper: The Sell swaps in shop/stores doesn't work.

### ISSUE THREAD

**Issue by GeChallengeM** [open-osrs/runelite#1597]
**Describe the bug**
The swaps Sell one, Sell five, Sell Ten and Sell Fifty don't work (in shop/stores).

**Screenshots**
Example:
https://i.imgur.com/u5xM0Il.png

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: up-to-date
 - Launcher version: up-to-date

**Comment by 5amchris** [comment]
Bump, Having this problem myself hopefully someone could look into it? Cheers team!

**Comment by Satamari** [comment]
Bump

**Comment by ReeeMan** [comment]
Is this every item in the shop or certain items?
Have you tried using a custom swap ?

**Comment by Satamari** [comment]
Buying works for all the items, selling does not, tested it with various items at several shops. Not sure what you mean by custom swap, this is what i tried (buying the iron knives works) https://i.imgur.com/ABsgjuW.png

**Comment by ReeeMan** [comment]
Yeah something is wrong somewhere...
for now try use prioritize Entry.

https://i.imgur.com/Rpk05N7.png
