### ISSUE TITLE
Interface Styles High Detail menu not working

### ISSUE THREAD

**Issue by Gravastar31415926535** [open-osrs/runelite#1620]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The Interface Styles High Detail menu will not work. Compared the exact settings to other client and turns out RL+ doesn't change the menu.
**To Reproduce**
1. Go to ''
2. Click on 'Interface Styles'
3. Scroll down to 'High detail menu and check it'

**Expected behavior**
The menu to change to an alternate Runescape look.
**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Lucwousin** [comment]
This is known, I'll maybe do it tomorrow if I think about it
