### ISSUE TITLE
RuneLite+ Not Working on my Mac OS Mojave

### ISSUE THREAD

**Issue by MacOSMojaveUser** [open-osrs/runelite#1622]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
1. Go to 'https://runelitepl.us/downloads'
2. Click on 'macOS'
3. Click on 'Jar Launcher'
4. Open 'RuneLitePlus.jar'
5. See error

**Expected behavior**
An error message appears and the application does not launch.
Console:
20:59:24.783879 -0700	syspolicyd	assessment denied for RuneLitePlus.jar but overridden
com.apple.message.domain: com.apple.security.assessment.outcome2
com.apple.message.signature2: bundle:UNBUNDLED
com.apple.message.signature3: RuneLitePlus.jar
com.apple.message.signature5: UNKNOWN
com.apple.message.signature4: 3
com.apple.message.signature: defeated:_XProtect
SenderMachUUID: 5D0A1EC6-519B-3224-84D1-59998AF98FD7

**Screenshots**
<img width="417" alt="Screen Shot 2019-09-18 at 9 14 16 PM" src="https://user-images.githubusercontent.com/55523863/65213605-a95f8780-da5b-11e9-8aa0-e39f58fcf41b.png">

<img width="1118" alt="Screen Shot 2019-09-18 at 9 31 13 PM" src="https://user-images.githubusercontent.com/55523863/65213614-afedff00-da5b-11e9-8491-cd9bb0641b7f.png">

**Environment (please complete the following information):**
 - OS: Mac OS Mojave
 - RuneLite+ 

Tried everything from compiling the source code on my own, to turning off my fire wall and more.

**Comment by Owain94** [comment]
You’re opening that jar file with the super old and outdated Apple java that is version 1.8

Try opening the launcher jar with java 11
