### ISSUE TITLE
Withdraw X from RL+ bank tab error

### ISSUE THREAD

**Issue by Lookout69** [open-osrs/runelite#1644]
**Describe the bug**
Withdrawing X from the RL+ bank tabs will leave the tab and return to the standard bank.

**To Reproduce**
1. Go to a bank.
2. Click on a custom bank tab on the left of the bank interface.
3. Withdraw X of any item/amount

**Expected behavior**
X amount of item is withdrawn from the bank while remaining in the bank tab.

**Screenshots**
Here's a GIF 
https://imgur.com/tlKi6nx

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.33
 - Launcher version: 1.5.33
[client.log](https://github.com/runelite-extended/runelite/files/3647001/client.log)
[launcher.log](https://github.com/runelite-extended/runelite/files/3647002/launcher.log)

**Comment by f0rmatme** [comment]
"RL+ bank tabs", bank tabs are part of the base runelite client.

Not sure if this is a runeliteplus bug

**Comment by Crystalknoct** [comment]
Is someone willing to sacrifice time to test on rl?
