### ISSUE TITLE
Mixin method static net/runelite/mixins/RSClientMixin.rl$menuAction(IIIILjava/lang/String;Ljava/lang/String;II)V should be non-static

### ISSUE THREAD

**Issue by joshuataylor** [open-osrs/runelite#1645]
**Describe the bug**
Can't compile on archlinux.

net.runelite.injector.InjectionException: Mixin method static net/runelite/mixins/RSClientMixin.rl$menuAction(IIIILjava/lang/String;Ljava/lang/String;II)V should be non-static
> Mixin method static net/runelite/mixins/RSClientMixin.rl$menuAction(IIIILjava/lang/String;Ljava/lang/String;II)V should be non-static

https://scans.gradle.com/s/3q5jhscv2oyqy/failure?openFailures=WzBd&openStackTraces=WzJd#top=0

openjdk 11.0.4

**To Reproduce**
Try and install on ArchLinux.

https://scans.gradle.com/s/3q5jhscv2oyqy/failure?openFailures=WzBd&openStackTraces=WzJd#top=0

**Comment by joshuataylor** [comment]
Why was this closed? It still happens, even on Ubuntu.

**Comment by pklite** [comment]
iirc, this was a problem from using openjdk. can you try using Zulu jdk from https://cdn.azul.com/zulu/bin/zulu11.33.15-ca-fx-jdk11.0.4-linux_x64.tar.gz ?

**Comment by Lucwousin** [comment]
This had to do with differing implementations of hash sets/maps between jvm versions. Either way, this has been fixed for a while now
