### ISSUE TITLE
Cerberus: add countdowns to next triple attack / Arooooo / Grrrrrr

### ISSUE THREAD

**Issue by GeChallengeM** [open-osrs/runelite#1654]
Update Cerberus plugin to show attacks left till next ghosts set spawn, next lavapool spawn and next triple attack. 
Unlike what most people believe, these things depend on the amount of attacks Cerberus has done, and NOT on a timer. 

How cerb works:
There's a attack counter starting at 0. Every time does a triple attack, normal attack, Aroooo or Grrrrrr, the counter increases by 1:
```
counter=0
While cerb is alive:
     If counter%10==0:  
          Next attack will be a triple attack.
     Else if counter%7==6 AND cerbHP<400:  
          Next attack will be Arooooo
     Else if counter%5==4 AND cerbHP<200:  
          Next attack will be Grrrrrr
     Else: 
          Next attack will be an auto attack
     Counter+=1
```
Ghosts do not always seem to spawn when they meet those requirements, not sure why, it's either random or something we can find in #pve-testing discord. It seems to only happen if cerb's last attack before the usual Aroooo is a magic attack (but it does not always happen if that's the case).

Here's how it starts, most ppl always finish the kill before the end of this list:
triple
auto
auto
auto
Grrrrrr
auto
Arooo
auto
auto
Grrrrrr
triple
auto
auto
Arooo
Grrrrrr
auto
auto
auto
auto
Grrrrrr
triple
(Replace Grrrrr and Arooo by auto if they don't meet the hp requirement)

**Comment by throwaway962** [comment]
If the plugin was updated to this, you shouldn't be taking any dmg correct?

**Comment by GeChallengeM** [comment]
You still take damage from the auto attacks because those are random mage/melee/ranged. 
But you can:
- Run on the tick lava pools spawn, avoiding that damage (unless you run in another badly placed pool)
- Know when cerb does its triple attack, allowing you to take 0 damage from that (can already be detected without countdown because it starts 1 tick later than usual attacks, but still nice to have).
