### ISSUE TITLE
PluginManager uses getSimpleName instead of @plugindescriptor

### ISSUE THREAD

**Issue by Fred4106** [open-osrs/runelite#1700]
**Describe the bug**
Two plugins that are in separate packages, with separate @plugindescriptor names ("Blackjack" vs "FredsBlackjack" in my case), but with the same class name ("BlackjackPlugin.java"), conflict silently behind the scenes.

**To Reproduce**
1. Create two duplicate plugins, but with seperate packages and @plugin descriptor names.
2. Build & Run Runelite
3. Turn both plugin's off in the sidebar.
4. Enable just one plugin in the sidebar.
5. Observe both plugins enable.

**Expected behavior**
Plugin state should be using the name from the plugindescriptor's name field instead of getSimpleName().

**Screenshots**
https://media.giphy.com/media/U7gS1jEQQBWwrXMSWO/giphy.gif

**Additional Info**
This is admittedly not a pressing issue, but it would be nice to fix. I'm mostly just worried about how we can either A, stay comparable with runelite's config files, and B, how to continue supporting loading old style configs.

**Comment by xKylee** [comment]
whilst an annoyance, it isn't an issue. If you're using an external plugin or building yourself, name the  files differently.
