### ISSUE TITLE
Koschei the deathless "hp indicator"

### ISSUE THREAD

**Issue by ScrPits** [open-osrs/runelite#1716]
**Describe the bug**
Koschei the deathless has 4 forms with the last form making his hp 255. the npc hp indicator doesnt pull that info?

**To Reproduce**
1. Go to 'fight Koschei the deathless via Fremennik Trials"
2. Kill him 3 times
3. attempt to kill forth time
4. See error in hp indicator showing his normal hp and not his new form hp

**Expected behavior**
Show the correct hp values..? 

No more info needed i dont believe.

**Comment by xKylee** [comment]
this is auto pulled from the wiki.
