### ISSUE TITLE
Anti-drag bug!!!

### ISSUE THREAD

**Issue by Crystalknoct** [open-osrs/runelite#1726]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Turning on Toggle anti-drag in anti-drag plugin functions like hold to anti-drag instead of toggle. Currently if you enable it works as anti-drag fine just requires you to hold instead of just toggle as suggested. Was working before the rl+ merge I believe. It seems if I hold down ctrl + shift it can enable it for some reason.
**To Reproduce**
1. Go to 'Anti-drag plugin'
2. Click on *https://i.imgur.com/MMtCVEW.png*
3. Scroll down to 'in game try to use toggle'
None is produced that I can see.
**Expected behavior**
As in the past enabling this feature would work fine however now it seems to be malfunctioning.
**Screenshots**

https://i.imgur.com/Lrq1a33.gifv
https://i.imgur.com/sb8cfbg.gifv
**Environment (please complete the following information):**
 - OS: [windows 10]
 - RuneLite version: [1.5.35]
 - Launcher version: [2.1.6.0]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
[launcher.log](https://github.com/open-osrs/runelite/files/3694059/launcher.log)
[application.log](https://github.com/open-osrs/runelite/files/3694060/application.log)
[client.log](https://github.com/open-osrs/runelite/files/3694061/client.log)

**Comment by Lucwousin** [comment]
This would be fixed by #1721
