### ISSUE TITLE
Clan chat name doubling when "show clan rank" is on

### ISSUE THREAD

**Issue by iGrow123** [open-osrs/runelite#1730]
**Describe the bug**
When you ask the overlay to put names above heads for clan memebrs, it doubles their name in order to reproduce the clan rank, instead of simply adding the badge beside their name.

**Screenshots**
![image](https://user-images.githubusercontent.com/56235163/66275230-91a64280-e854-11e9-9634-20736efd5e8f.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.35
 - Launcher version: 2.1.6.0

**Additional context**
![image](https://user-images.githubusercontent.com/56235163/66275230-91a64280-e854-11e9-9634-20736efd5e8f.png)

**Comment by Crystalknoct** [comment]
This still an issue? I havnt been able to reproduce at all lately.

**Comment by GrimWrath** [comment]
I haven't seen it appear since a week or two since I posted this issue.
