### ISSUE TITLE
MacOS GPU Port

### ISSUE THREAD

**Issue by stevebasher** [open-osrs/runelite#1736]
**Is your feature request related to a problem? Please describe.**
The GPU feature is often said to be one of the best that RL (and now OpenOSRS) offer, but alas it doesn't exist for MacOS users like myself. Any chance this is a do-able port that could be worked on?

**Describe the solution you'd like**
A matching feature set would be ideal, allowing better graphics, reduction in CPU usage, extended render distances etc.

**Describe alternatives you've considered**
Being sad at my sub-par MacOS experience.

**Comment by weblue** [comment]
It's been brought up before, but MacOS doesn't support the GPU plugin. MacOS has deprecated OpenGL and doesn't seem to care enough to update it to a version compatible with the GPU plugin. Until Apple makes a change or someone starts porting OpenGL to Mac, this will never happen.

**Comment by Owain94** [comment]
Or the GPU plugin code is downgraded to a version that doesn't use compute shaders, or the GPU plugin is rewritten to vulkan

**Comment by weblue** [comment]
gpu plugin rewritten to vulkan would be the nut

**Comment by IanWONeill** [comment]
https://github.com/LWJGL/lwjgl3-demos/tree/master/src/org/lwjgl/demo/vulkan

**Comment by xKylee** [comment]
unfortunately, i cannot see ourselves re-writing the entire GPU plugin to accomodate this.

AFAIK, there is an open bounty on re-writing it within the runelite discord where people are putting cash into a pot in hopes someone will do so.

**Comment by Grandmasboi** [comment]
can one not just buy a external mini tower and run a Mac off a ogpu and high end graphics card to fix this issue or would one need to download windows 10 with parrallels too

**Comment by Grandmasboi** [comment]
can one not just upgrade to a external gpu and graphics video card like high end nividia or radeon to work or would I need to download windows 10 if I go that route
