### ISSUE TITLE
player indicator not working w345 deadman mode

### ISSUE THREAD

**Issue by Topsy45** [open-osrs/runelite#1740]
The plugin stopped highlighting 100% of all people on the >other option of the player indicators plugin. This happened the last update pre-oprs and is still the same way. It used to work fine. Windows OS and I use the native launcher.

From what I noticed, it is just random whoever happens to not be highlighted.

**Comment by Topsy45** [comment]
I have now realized the plugin is only not highlighting people (random method stated above) but its only doing it on w345 deadman mode (the world it matters most on) and it works 100% fine on regular osrs. please fix this ASAP!

**Comment by xKylee** [comment]
can you confirm if this is still an issue?

**Comment by Topsy45** [comment]
hey sorry i forgot to update this, I was messing with the plugin and realized that you need to have 'other' and 'targets' enabled for it to work 100% on deadman mode, so it is working now if you enable 'targets' as well as 'other' make them both red lol (what i did)
