### ISSUE TITLE
Adjustable Client Audio devices

### ISSUE THREAD

**Issue by Hacon** [open-osrs/runelite#1784]
The ability to change the clients audio device from the default audio device windows has selected. This would allow content creators better management of there audio channel, while also benefiting anyone who uses even a speaker / headphone setup that doesnt want to constantly have to change there default audio device.

**Comment by ocekyled** [comment]
you can already do this under windows settings.
![Annotation 2019-10-15 033058](https://user-images.githubusercontent.com/19616058/66769353-7397ac80-eefc-11e9-9821-2efd2a30f683.png)
