### ISSUE TITLE
pvp tools hide cast

### ISSUE THREAD

**Issue by bubble333** [open-osrs/runelite#1826]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
hide cast does not work in pvp tools

**To Reproduce**
1. tick on hide cast in pvp tools,select any mode
2. use a cast on your friend/clan mate

**Expected behavior**
be unable to cast a spell on friend/clan mate

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by xKylee** [comment]
can you confirm this is still an issue please

**Comment by bubble333** [comment]
this has been fixed
