### ISSUE TITLE
war calling indicators

### ISSUE THREAD

**Issue by bubble333** [open-osrs/runelite#1830]
**Is your feature request related to a problem? Please describe.**
names appear behind skulls
![1](https://user-images.githubusercontent.com/35826890/67435846-a7d13400-f5b2-11e9-9688-770a99519bf0.PNG)

**Describe the solution you'd like**
have names appear on top of skulls

**Comment by xKylee** [comment]
can you confirm this is still an issue?

**Comment by bubble333** [comment]
yes
![1](https://user-images.githubusercontent.com/35826890/69449213-03aceb00-0d20-11ea-9e73-13b0faa729d5.PNG)

also some names dont highlight at all, example i have sensei elmo on the list but he doesnt highlight, but the others do
![2](https://user-images.githubusercontent.com/35826890/69449637-f5130380-0d20-11ea-8e2b-9497a60212ae.PNG)

**Comment by zeruth** [comment]
Issues with plugins that aren't allowed by Jagex / Adam won't be fixed here.
