### ISSUE TITLE
Stoned loot tracker using invalid json

### ISSUE THREAD

**Issue by Lucwousin** [open-osrs/runelite#1833]
So the loot files are not actually valid JSON... Which makes using JSONReader to read the files in a backwards compatible manner pretty difficult.

Here is an example loot file that contains both minified and pretty printed JSON (note the lack of a high level json array structure).

https://gist.github.com/tha23rd/b404a9a4e9e58ee56e9f5e1cb8a55258

(thanks to @tha23rd)

I think there's options in JsonReader to be lenient with top level classes, and even if not, just a quick regex looking for \}\n\{ and replacing with },{ and plopping a [ and a ] before/behind the string would fix it

**Comment by Owain94** [comment]
> When we updated google GSON this bug got introduced. Their old version allowed non valid json to be outputted and ingested, the new version however fixed this.
> 
> Because of that I added this dirty fix that allows ingesting the non valid json.
> 
> Converting it to valid json and append new loot to it creates the same problem we had with the local persistent loot tracker where it would lag badly because it has to ingest the json, append a new block and output it.
> 
> Reworking the plugin to work with the loottracker database is the best option imo but I’m not at all sure if the database is even used when local persistence is turned off in the loottracker. That’s easy to lookup though.
> 
> All data from stoned loot tracker has to be added to the database which will have to be deduplicated with local loottracker data that’s already present in the database in an ideal world (which might be impossible).
