### ISSUE TITLE
Opponent health bar overlapping with PVP k/d 

### ISSUE THREAD

**Issue by stevebasher** [open-osrs/runelite#1834]
**Describe the bug**
At the moment in PVP worlds I have a messy overlap of overlays in the top-left (see screenshot), any chance we could fix this?

**To Reproduce**
1. Go on PVP world with k/d enabled
2. Pot up / venge / pray with the overlays enabled
3. Fight someone and see the mess

**Screenshots**
![image](https://user-images.githubusercontent.com/8497007/67461737-f673e200-f635-11e9-82b5-aedbf6d5a243.png)
(It also overlaps onto an opponent health bar in the middle of the fight, which is more inconvenient)

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: 1.5.35-SNAPSHOT
 - OpenOSRS version: 2.1.7.0

**Comment by xKylee** [comment]
press and hold alt, and move them...

**Comment by stevebasher** [comment]
> press and hold alt, and move them...

Woah, did not realise this was a feature *facepalm*
