### ISSUE TITLE
Cox: name with spaces break teleport timer

### ISSUE THREAD

**Issue by emiljensen2** [open-osrs/runelite#1847]
**Describe the bug**
The teleport timer doesn't appear on players with space in their name.

**To Reproduce**
Enable cox helper with teleports help
go to olm with someone that has a space in their name.

**Expected behavior**
No timer shows.

Another discord user posted a streamable: [https://streamable.com/xumnq](url)

I posted this earlier in #1626 but the commit there didn't fix the issue.

**Comment by xKylee** [comment]
i thought this had been fixed, can you confirm its still an issue @emiljensen2

**Comment by emiljensen2** [comment]
@xKylee ReeeMan fixed it with his PR.
