### ISSUE TITLE
Building from source, Building from git

### ISSUE THREAD

**Issue by ScrPits** [open-osrs/runelite#1859]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
A more outlined building from source page, and a building from git page as these two work completely different.

**To Reproduce**
1. Build from source.
2. figure out how to get gradle to work
3. Get annoyed
4. Post here for info?

**Expected behavior**
Building from source not cryptic 

**Additional context**
I have tried multiple things to build from source, but im not getting the gradle to work correctly
While when i use git to build the gradle is picked up automatically

**Comment by ScrPits** [comment]
repository not found : files\runelite\ ect
^ seems to be one of the issues i am seeing alot. yet it list out where the "source file" is located

**Comment by f0rmatme** [comment]
join our discord for help
