### ISSUE TITLE
Ardougne cloak 4 MES bug

### ISSUE THREAD

**Issue by archa883** [open-osrs/runelite#1862]
I have seen this bug mentioned before so I have written steps to reproduce it. And believe me it's still there!
Whenever I set Ardougne cloak 4 to be in Farm teleport mode it switches to Monastery teleport forever if something is written in MES-> Banking -> Deposit/Withdraw all.
No other swaps for Ardougne cloak 4 have been set, even after removing every single swap it doesn't fix the bug. Only solution is to completely uninstall and reinstall OpenOSRS and not touch Deposit/Withdraw all.

**To Reproduce**
1. Go to Menu entry swapper
2. Click on Banking
3. Mark Deposit/Withdraw all
4. Put anything in the list. And it doesn't matter what. Even if later you remove checkbox mark or delete something from the list bug still persists. For ex. my list:

"Deposit-all, Superior dragon bones:0
Deposit-all, Rune longsword:0
Deposit-all, Rune kiteshield:0
Deposit-all, Battlestaff:0
Deposit-all, Dragon battleaxe:0
Deposit-all, Dragon longsword:0
Deposit-all, Dragon platelegs:0
Deposit-all, Dragon plateskirt:0
Deposit-all, Chaos rune:0
Deposit-all, Death rune:0
Deposit-all, Wrath rune:0
Deposit-all, Blue dragonhide:0
Deposit-all, Green dragonhide:0
Deposit-all, Red dragonhide:0
Deposit-all, Black dragonhide:0
Deposit-all, Dragon dart tip:0
Deposit-all, Dragonstone bolt tips:0
Deposit-all, Onyx bolt tips:0
Deposit-all, Rune dart tip:0
Deposit-all, Dragon arrowtips:0
Deposit-all, Diamond bolt tips:0
Deposit-all, Emerald bolt tips:0
Deposit-all, Ruby bolt tips:0
Deposit-all, Sapphire bolt tips:0
Deposit-all, Dragon bolts (unf):0
Deposit-all, Adamantite ore:0
Deposit-all, Grapes:0
Deposit-all, Magic logs:0
Deposit-all, Diamond:0
Deposit-all, Dragonstone:0
Deposit-all, Snapdragon seed:0
Deposit-all, Torstol seed:0
Deposit-all, Ranarr seed:0
Deposit-all, Watermelon seed:0
Deposit-all, Willow seed:0
Deposit-all, Mahogany seed:0
Deposit-all, Maple seed:0
Deposit-all, Teak seed:0
Deposit-all, Yew seed:0
Deposit-all, Papaya tree seed:0
Deposit-all, Magic seed:0
Deposit-all, Palm tree seed:0
Deposit-all, Spirit seed:0
Deposit-all, Dragonfruit tree seed:0
Deposit-all, Celastrus seed:0
Deposit-all, Redwood tree seed:0
Deposit-all, Coins:0
Deposit-all, Manta ray:0
Deposit-all, Dragon bones:0
Deposit-all, Wrath talisman:0
Deposit-all, Loop half of key:0
Deposit-all, Tooth half of key:0
Deposit-all, Vorkath's head:0
Deposit-all, Adamant javelin:0
Deposit-all, Adamantite bar:0
Deposit-all, Antidote++(4):0
Deposit-all, Calquat tree seed:0
Deposit-all, Coal:0
Deposit-all, Coconut:0
Deposit-all, Crystal key:0
Deposit-all, Crystal seed:0
Deposit-all, Dragon halberd:0
Deposit-all, Dragon med helm:0
Deposit-all, Dwarf weed seed:0
Deposit-all, Dwarf weed:0
Deposit-all, Flax:0
Deposit-all, Jar of swamp:0
Deposit-all, Law rune:0
Deposit-all, Magic fang:0
Deposit-all, Mahogany logs:0
Deposit-all, Nature talisman:0
Deposit-all, Pure essence:0
Deposit-all, Rune 2h sword:0
Deposit-all, Rune arrow:0
Deposit-all, Rune battleaxe:0
Deposit-all, Rune javelin:0
Deposit-all, Rune sq shield:0
Deposit-all, Runite bar:0
Deposit-all, Runite ore:0
Deposit-all, Serpentine visage:0
Deposit-all, Silver ore:0
Deposit-all, Snakeskin:0
Deposit-all, Snapdragon:0
Deposit-all, Swamp tar:0
Deposit-all, Tanzinite fang:0
Deposit-all, Toadflax seed:0
Deposit-all, Toadflax:0
Deposit-all, Torstol:0
Deposit-all, Uncut onyx:0
Deposit-all, Yew logs:0
Deposit-all, Zul-andra teleport:0
Deposit-all, Zulrah's scales:0"

**Environment:**
 Windows 10
 - OpenOsrs version: 2.1.7.0
 -Build date: 10-15-2019
 - Launcher version: newest

**Comment by Coollegolas** [comment]
Farm Teleport, Ardougne Cloak 4:101

**Comment by archa883** [comment]
> Farm Teleport, Ardougne Cloak 4:101

Doesn't fix the problem
