### ISSUE TITLE
GPU Plugin - Chatbox issue

### ISSUE THREAD

**Issue by xL1V1NxL3G3NDx** [open-osrs/runelite#1867]
**Describe the bug**
When having the GPU plugin enabled, with the transparent chatbox in the OSRS settings, the chatbox becomes solid black - instead of having transparency. 

**To Reproduce**
1. Enable GPU plugin
2. Enable resizeable-mod transparent chatbox

**Screenshots**
https://i.imgur.com/u3qEZiI.png

**Environment (please complete the following information):**
 - OS: Win10
 - RuneLite version: Latest (was working fine yesterday)

**Comment by Lucwousin** [comment]
fixed with #1869
