### ISSUE TITLE
Is there any affiliation with current runeliteplus?

### ISSUE THREAD

**Issue by tacocats** [open-osrs/runelite#1871]
I recently saw that someone released a injector under the name "runeliteplus"
It's website is https://runelite.plus/

I also noticed the name of this project was changed recently to open-osrs instead of runeliteplus, which is something I feel was a good decision since this is not affiliated with runelite itself. Is runeliteplus a project by this community or is it something jumping on the name?

**Comment by xKylee** [comment]
No, nothing to do with us.
