### ISSUE TITLE
Priffdinnis is still broken and my last reported issue was ignored!

### ISSUE THREAD

**Issue by ljmclsc** [open-osrs/runelite#1876]
Priff is broken still... All NPCs are in the air including me and I can't interact with anything! Why did "Lucwousin" close the issue instead of answering what is wrong with it. I find that very unprofessional. What's the point in this part of the process if no-one replies. 
Proof of broken priff in the link:

[](https://ibb.co/RPMH9R7)

**Comment by ljmclsc** [comment]
https://ibb.co/RPMH9R7

**Comment by Ganom** [comment]
Because you're likely using an outdated client bud, its fixed on the master repo, and the updated launcher. Please check the announcements in discord.

**Comment by ljmclsc** [comment]
I uninstalled and reinstalled a few times surely that would have updated the client? is there a link you may share so I can check if this fixes the problem, please. I enjoy using this client which made me all the more upset when I came looking for help online and was just ignored. :(

**Comment by Ganom** [comment]
> I uninstalled and reinstalled a few times surely that would have updated the client? is there a link you may share so I can check if this fixes the problem, please. I enjoy using this client which made me all the more upset when I came looking for help online and was just ignored. :(

https://github.com/open-osrs/launcher/releases/tag/2.1.9.0

**Comment by ljmclsc** [comment]
Thank you. I hope this will end my problem if so I will let you know and close the issue.

**Comment by f0rmatme** [comment]
please join our discord if you have any issues.
