### ISSUE TITLE
Easyscape Plugin missing?

### ISSUE THREAD

**Issue by ljrobison** [open-osrs/runelite#1922]
Hello, I'm not sure if this is the correct place to ask this question, but I could not find any community forums or anything.

I cannot seem to find the Easyscape plugin that is advertised in the features. Specifically I cannot find the one click construction plugin. Is it no longer available? Or can someone show me where I can find that plugin?

Thank you.

**Comment by Owain94** [comment]
The feature of the easyscape plugin have been merged with the menu entry swapper plugin. You can find them in the settings of that plugin.

**Comment by ljrobison** [comment]
Thank you so much! What a quick answer too.
