### ISSUE TITLE
Protect item spam in Bounty Hunter

### ISSUE THREAD

**Issue by markbrandly** [open-osrs/runelite#1967]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
When I go into the wilderness on bounty hunter, I get constant Protect Item prayer messages, as if the client is trying really hard to turn protect item off. Whale Watchers plugin is not on, however.

I'm under 25 prayer, so can't use protect item. It's likely trying to turn it on constantly since it's off

**To Reproduce**
Go into w319 wilderness while <25 prayer. I don't believe I've activated any plugins that aren't turned on automatically

**Screenshots**
https://gyazo.com/e84279abc67019b796fc43f941db4055

**Environment (please complete the following information):**
 - OS: Windows 10
 - 1.5.39
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Ganom** [comment]
Remove any external plugins and see if this problem persists, but as of now, this is invalid.

**Comment by Ganom** [comment]
![image](https://user-images.githubusercontent.com/8338284/68519355-77e68980-025e-11ea-8eee-fb3a5c156e00.png)
