### ISSUE TITLE
playermanager: plugins that still need updated.

### ISSUE THREAD

**Issue by Ganom** [open-osrs/runelite#1987]
- [ ] Clan Man Mode
- [ ] FreezeTimers
- [ ] PvP Tools
- [ ] Whale Watchers
- [ ] War Indicators

If anyone outside of the org would like to assist, that'd be greatly appreciated <3

**Comment by f0rmatme** [comment]
Player Indicators?

**Comment by xKylee** [comment]
Freezetimers can be ignored I think seeing as we will end up swapping to status timers as it’s buggy af
