### ISSUE TITLE
"Null" items appear on ground when players die

### ISSUE THREAD

**Issue by 403-Fruit** [open-osrs/runelite#2072]
**Describe the bug**
In clan wars, every time a player dies a "null" item (Item ID 1768515945) appears where they died. Not able to pick up or examine the item. May be exclusive to clan wars. I haven't tested elsewhere, but it doesn't happen in Last Man Standing. Only happens on openosrs client.  

Nothing obvious in the logs but I've attatched them just in case.  

**To Reproduce**
1. Go to clan wars
2. Wait for someone to die

**Screenshots**
![shot0002](https://user-images.githubusercontent.com/46859125/69490863-a012e280-0e31-11ea-9168-a0106b1054e0.jpg)
![shot0004](https://user-images.githubusercontent.com/46859125/69490864-a012e280-0e31-11ea-9c5f-b889afe1635e.jpg)
![shot0001](https://user-images.githubusercontent.com/46859125/69490866-a0ab7900-0e31-11ea-98c2-e877062d97fa.jpg)
![shot0005](https://user-images.githubusercontent.com/46859125/69490865-a012e280-0e31-11ea-8aab-80be66de6472.jpg)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.42-SNAPSHOT
 - Launcher version: 2.1.14.0

**Additional context**
Client log: [client.log](https://github.com/open-osrs/runelite/files/3883294/client.log)

**Comment by supermxn** [comment]
Look in Death Indicator plugin

**Comment by Lucwousin** [comment]
Is already fixed. Item ID is 0x69696969 btw
