### ISSUE TITLE
XP Drop: Show Damage

### ISSUE THREAD

**Issue by SRLJustin** [open-osrs/runelite#2078]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
Show Damage option does nothing since recent update

**To Reproduce**
Enable XP Drop Plugin
Enable Show Damage dropdown -> In Xp Drop

**Expected behavior**
The Damage show in () after the xp drop

**Screenshots**

https://i.imgur.com/RT9LVzN.png

prior update:
https://i.imgur.com/ksI9hfK.png

**Comment by xKylee** [comment]
can you confirm if this works in twisted leagues? or if its broken completely? 

could you also test making line 364 to an else if and see if that resolves the issue?

**Comment by SRLJustin** [comment]
@xKylee Twisted league worlds do not show the Damage drop (no modification to the plugin)

Adding the 'else' to line 364 still doesn't make the Damage drop show in Twisted League or the main game.
