### ISSUE TITLE
Multi lines plugin tlc

### ISSUE THREAD

**Issue by Topsy45** [open-osrs/runelite#2080]
So I noticed back when zeah got rearranged that the multi lines plugin did not have the correct and updated multi lines on the rearranged zones, so I am making this post to get these updated ty.

Just go outside the zeah house portal and check there are multi spots just south and one east of the farming spot to the north.

I use the .exe stable.

**Comment by xKylee** [comment]
can you provide a list of all locations where they are out of date? i'm being honest, i'm not going to walk round zeah to try and map them correctly :)

**Comment by stone-wall** [comment]
better yet, use my fork of https://github.com/stone-wall/Explv.github.io and draw them then export to RunelitePlust format and paste them here 🥇

**Comment by Topsy45** [comment]
![multi1](https://user-images.githubusercontent.com/42102931/69909701-22f8e780-13b4-11ea-88b1-49229236ee30.png)
![multi2](https://user-images.githubusercontent.com/42102931/69909702-24c2ab00-13b4-11ea-8e83-a56618080c19.png)
![multi3](https://user-images.githubusercontent.com/42102931/69909703-268c6e80-13b4-11ea-8aad-034fcc57a688.png)
![multi4](https://user-images.githubusercontent.com/42102931/69909704-28563200-13b4-11ea-992a-79f645ae8204.png)
![multi5](https://user-images.githubusercontent.com/42102931/69909705-28eec880-13b4-11ea-9c2b-4874b029c5ed.png)
![multi6](https://user-images.githubusercontent.com/42102931/69909707-2c824f80-13b4-11ea-8a37-cc43c8149324.png)
![multi7](https://user-images.githubusercontent.com/42102931/69909708-3015d680-13b4-11ea-978a-cbbb56c67e3d.png)
![multi8](https://user-images.githubusercontent.com/42102931/69909709-31df9a00-13b4-11ea-8b15-467348187746.png)
![notmulti1](https://user-images.githubusercontent.com/42102931/69909710-3310c700-13b4-11ea-95db-96443fe4b6b0.png)
![notmulti2](https://user-images.githubusercontent.com/42102931/69909711-3441f400-13b4-11ea-9cd0-49f6bd766514.png)

**Comment by xKylee** [comment]
@Topsy45 im going to be an arsehole here, any chance you can mark them with https://explv.github.io/ it will output it like this:

`Area[] area = {
    new Area(3021, 3353, 3008, 3358),
    new Area(3003, 3374, 3005, 3372),
    new Area(3045, 3367, 3050, 3361)
};`

which is alot easier to add, it also ensures that what you;re seeing is added corectly, and isnt mis-drawn and added by me.

i also don't believe that mount karluum is done either.

**Comment by Topsy45** [comment]
Not all could be done with format you used because its not perfect square or rectangle so used the other options to mark accurately

Area area = new Area(1742, 3556, 1761, 3543);

Area area = new Area(1664, 3541, 1683, 3583);

Position[] path = {
    new Position(1757, 3492, 0),
    new Position(1756, 3493, 0),
    new Position(1756, 3499, 0),
    new Position(1754, 3501, 0),
    new Position(1751, 3501, 0),
    new Position(1749, 3503, 0),
    new Position(1745, 3503, 0),
    new Position(1744, 3504, 0),
    new Position(1741, 3504, 0),
    new Position(1740, 3503, 0),
    new Position(1739, 3503, 0),
    new Position(1738, 3502, 0),
    new Position(1737, 3502, 0),
    new Position(1732, 3497, 0),
    new Position(1732, 3492, 0),
    new Position(1733, 3491, 0),
    new Position(1733, 3489, 0),
    new Position(1734, 3488, 0),
    new Position(1734, 3487, 0),
    new Position(1737, 3487, 0),
    new Position(1738, 3486, 0),
    new Position(1745, 3486, 0),
    new Position(1746, 3485, 0),
    new Position(1749, 3485, 0),
    new Position(1750, 3486, 0),
    new Position(1753, 3486, 0),
    new Position(1754, 3487, 0),
    new Position(1756, 3487, 0),
    new Position(1756, 3491, 0),
    new Position(1757, 3492, 0)
};

Position[] path = {
    new Position(1776, 3513, 0),
    new Position(1773, 3513, 0),
    new Position(1772, 3512, 0),
    new Position(1768, 3512, 0),
    new Position(1768, 3510, 0),
    new Position(1767, 3509, 0),
    new Position(1767, 3501, 0),
    new Position(1768, 3500, 0),
    new Position(1772, 3500, 0),
    new Position(1773, 3499, 0),
    new Position(1780, 3499, 0),
    new Position(1782, 3501, 0),
    new Position(1783, 3501, 0),
    new Position(1783, 3511, 0),
    new Position(1780, 3511, 0),
    new Position(1779, 3512, 0),
    new Position(1777, 3512, 0),
    new Position(1776, 3513, 0)
};

Position[] path = {
    new Position(1792, 3497, 0),
    new Position(1806, 3497, 0),
    new Position(1806, 3485, 0),
    new Position(1812, 3485, 0),
    new Position(1812, 3471, 0),
    new Position(1810, 3471, 0),
    new Position(1809, 3472, 0),
    new Position(1808, 3472, 0),
    new Position(1806, 3474, 0),
    new Position(1805, 3474, 0),
    new Position(1804, 3475, 0),
    new Position(1800, 3475, 0),
    new Position(1799, 3476, 0),
    new Position(1792, 3476, 0),
    new Position(1792, 3497, 0)
};

Position[] path = {
    new Position(1855, 3466, 0),
    new Position(1855, 3470, 0),
    new Position(1833, 3470, 0),
    new Position(1855, 3466, 0)
};

Position[] path = {
    new Position(1846, 3548, 0),
    new Position(1848, 3548, 0),
    new Position(1850, 3550, 0),
    new Position(1850, 3552, 0),
    new Position(1851, 3553, 0),
    new Position(1851, 3556, 0),
    new Position(1850, 3557, 0),
    new Position(1850, 3558, 0),
    new Position(1851, 3559, 0),
    new Position(1851, 3562, 0),
    new Position(1848, 3562, 0),
    new Position(1844, 3566, 0),
    new Position(1844, 3567, 0)
};

Area area = new Area(
    new int[][]{
        { 1648, 3647 },
        { 1626, 3647 },
        { 1626, 3637 },
        { 1648, 3637 },
        { 1648, 3632 },
        { 1649, 3632 },
        { 1649, 3647 }
    }
);

**Comment by xKylee** [comment]
this is no longer a openosrs supported plugin.
