### ISSUE TITLE
Player Scouter Issue

### ISSUE THREAD

**Issue by Lordaos** [open-osrs/runelite#2107]
Prior to the recent update I was running Player Scout plugin simultaneously on two different accounts. They were periodically (every 10 seconds or so) hopping worlds and outputting the data into discord. Until the update, it was flawless. Now it rarely detects players at all. I have tested in different locations (wildy vs non wildy) and don't have any really conclusive results. Non-wild was functioning. Wild was only partially functional.

I hope that this is addressed and resolved.
Thanks

**Comment by Lucwousin** [comment]
Is this maybe caused by jagex throttling requests more cause of current instability?

**Comment by Ganom** [comment]
Definitely possible, but i'll check and see whats going on and if i can reproduce the issue on my end.

**Comment by Lordaos** [comment]
![image](https://user-images.githubusercontent.com/58627301/70490397-f712fa00-1b49-11ea-9bba-9a7605cb1731.png)
Here is an example.

**Comment by Lordaos** [comment]
> Definitely possible, but i'll check and see whats going on and if i can reproduce the issue on my end.

Any news?

**Comment by xKylee** [comment]
this is no longer a openosrs supported plugin.
