### ISSUE TITLE
Shamans timer bugged

### ISSUE THREAD

**Issue by schokkya** [open-osrs/runelite#2108]
![bug](https://user-images.githubusercontent.com/21267252/70381169-1b05ee00-1946-11ea-99ee-3e96f6a70a09.png)

I was at shamans earlier, went to a different area and logged out. Logging back in and I was greeted with these timers showing around the area. Disabling the shamans plugin and enabling it again makes it disappear.

**Comment by dutta64** [comment]
#2175 This should be a non-issue now and closed.
