### ISSUE TITLE
Banlist: WDR banlist: User who is under toxic section is being listed as under scammer section

### ISSUE THREAD

**Issue by GrimWrath** [open-osrs/runelite#2115]
Username is Culmoor - is on toxic list but is showing up as on scammer list instead now; potential serious issue here if it is affecting other people. Have confirmed with wdr staff that he is not on scammer list.

**Comment by Owain94** [comment]
https://wdrdev.github.io/toxic

The above url is WDR their toxic list, Culmoor is not on there

https://wdrdev.github.io/

This url is their scan list and Culmoor is on that list

Last time someone complained about being on the list some of their moderators didn't even know about the lists they have on GitHub, you might want to contact someone higher up.
