### ISSUE TITLE
Bring back old pray vs other please

### ISSUE THREAD

**Issue by donni1** [open-osrs/runelite#2133]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.can the old pray vs other be added where it showed what to pray above ur targets head depending on what weapon he was wielding, willing to pay for this to be added back. Please and thanks 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**
Will pay for old pray vs other to be added back instead of the new one that highlights attacker. In my opinion, the old pray vs other where it showed what to pray above targets head based on what weapon was wielded was so much better

**Comment by Owain94** [comment]
No information or whatsoever given about why the old plugin was better in the opinion of the issue opener, therefore closing this issue

**Comment by xKylee** [comment]
The old one would draw the pray sprite on the attacking player. For some this was better than highlighting the pray tab due to muscle memory. Imo, it’s a feature that should have remained. I’ll look at adding it back at some point

**Comment by zeruth** [comment]
This is a compliance related plugin and we will not be working to improve it when it's pending removal entirely.
