### ISSUE TITLE
fairy ring codes on worldmap broken

### ISSUE THREAD

**Issue by badtimesz** [open-osrs/runelite#2138]
![72uAsXv](https://user-images.githubusercontent.com/58965571/70964312-a50f2e80-208b-11ea-9a05-a10c94e888c2.png)
fairy ring codes aren't shown on worldmap 'transportation' - symbol.

**Comment by Ganom** [comment]
During the rev update today, some of the world map deobfuscation failed, as such world map is broken atm. We're working on a fix, and appreciate your patience.
