### ISSUE TITLE
Hydra helper for regular hydras

### ISSUE THREAD

**Issue by Abi1024** [open-osrs/runelite#2152]
**Is your feature request related to a problem? Please describe.**
Similar to the features provided by the Alchemical Hydra, such as showing which prayer to use and where the poison will appear, it would be nice to have a plugin which shows the same things for the regular hydras (as opposed to the boss variant). 

Currently, the plugin has the features only for the boss variant.

**Describe the solution you'd like**
AoE indicator and prayer indicator for regular hydras.

**Additional context**
I will probably end up doing this myself if no one else wants to.

**Comment by Crystalknoct** [comment]
Some of this is already working only thing that needs to be added is aoe, https://i.imgur.com/PmP72zJ.gifv

**Comment by Lucwousin** [comment]
This is what the baby hydra plugin (is supposed to) do. That plugin has always been kinda bad though, so adding it on to the alchemical hydra plugin would be a nice improvement (being able to reuse logic etc).

**Comment by Crystalknoct** [comment]
Wouldnt be too difficult either since the little ones have the same 1,2,3 attack style just not sure on their poison attack myself.

**Comment by Lucwousin** [comment]
Think that's all exactly the same as daddy hydra. Seeing as how I made hydra, I'll do it unless someone else wants to claim it real quick

**Comment by xKylee** [comment]
this is no longer a openosrs supported plugin.
