### ISSUE TITLE
Loot Tracker Inconsistency (?)

### ISSUE THREAD

**Issue by Infinitay** [open-osrs/runelite#2176]
This is going to get confusing very fast, I'll try to keep the logic as clear as I can, but really it's all messed up and confusing, bear with me please. Also, I should add that I haven't been involved with RL/OpenOSRS for a long while now, but I tried catching up and seeing the changes, such as migrating to a db instead of json for `Loot Tracker`.

# Saving Data
On my main, I noticed that my kills aren't being logged to it's own file, its just going into `/loots` and not `/loots/<my_main_ign>`, **but** a folder **does exist** with my ign `/loots/my_main_ign`, and it's reading **some** of the kills in them. For instance, I have a list of `.log`'s from bosses that I put in there, and they don't show up in the Loot Tracker plugin. However, a `guard.log` is being read just fine, despite being both in `/loots/guard.log` and `/loots/<my_main_ign>/guard.log`. In addition to this, when I log into an alt account, the client recognizes that `/loots/guard.log` is not it's log and instead it looks within `/loots/<my_alt_ign/guard.log`. More on this later as I think it's because of the database file `/RunelitePlus.mv.db`.

Back to what I was discussing prior: For example, I killed 2 guards and its loot is saved in `/loots`, and then I killed another **AFTER** logging into and out of an **alt** account. Only **then** did it save the next guard I killed in `/loots/<my_main_ign>/guard.log`. This is inconsistent behavior as I believe it should always save the loot logs within the respective folder associated with the current player logged in.

---

# Clearing Data
If I clear data via the Loot Tracker plugin, it doesn't get delete any of the `.log` files stored in `/loots`. Therefore, Stoned's Tracker stays in tact, this makes sense. What doesn't make sense is if we are adding to `/loots`/ `/loots/<ign>`, why are we also adding the logging of the kills to our `/RunelitePlus.mv.db`? This just makes the entire process even more confusing and just tangles everything up with their inconsistencies.

---

# `/RunelitePlus.mv.db`
Apparently this is the file that the Loot Tracker plugin actually utilizes to log our looting data. It gets updates when I receive loot or if I clear the data. Which brings me back to the other point as mentioned in Clearing Data: why are we also logging the kills within `/loots`/ `/loots/<ign>`? I assume it's because of Stoned's tracker.

---

# Conclusion
The problem I am trying to address is the inconsistency of where and how the loot tracking data are being stored for all associated plugins such as `Loot Tracker` and `Stoned Tracker`. As of writing this, I am beginning to come to the conclusion that the `.log` files are in fact associated `Stoned Tracker` because [`LootTracker/localstorage/LootRecordWriter.java` doesn't seem to be used any longer which previously stored the `.log` file within `/loots/<ign>`](https://github.com/open-osrs/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/loottracker/localstorage/LootRecordWriter.java#L52). Therefore, I think the problem lies within `Stoned Tracker` for the `.log` saving inconsistencies.

Although, because we have already migrated to saving `Loot Tracker`'s data into a database, **why don't we also migrate `Stoned Tracker` to using a database as well**? We could have two files, appropriately named `/loottracker.mv.db` and `/stonedtracker.mv.db`. Cleaner, seems simpler, and should get rid of the inconsistencies.

**Comment by Owain94** [comment]
I think the best thing to do would be making both plugins use the same database and the same database entries 

This was the plan to do a long while ago

The current way loot is being saved is awful there are multiple different ways of saving loot 

Converting them all to just use the database would be the best thing to do imo and the database already stores all data that would be needed for other plugins (stoned comes to mind) I think

**Comment by stone-wall** [comment]
Yeah I agree, IIRC the stoned tracker uses loot events which is just duplicating events on the eventbus if not a bit redundant/wasteful since they were just being created from the firing of other different events. 

i am pretty sure the author of the stoned tracker updates the plugin independently and we just get their changes from their repo so converting it to use our could possibly just create more work in future when merging changes. if its possible maybe we should try and get into contact with the author and see if he would want to implement the db changes into his own plugin or maybe even consolidate the two plugins by adding the stone user interface as an alternative configurable option to the built in tracker
