### ISSUE TITLE
Crash to Desktop on Stable

### ISSUE THREAD

**Issue by Gamer1120** [open-osrs/runelite#2180]
Was runecrafting at ZMI, crashed to desktop. Log attached. Nothing in client, application or launcher.log.
[jvm_crash_pid_17164.log](https://github.com/open-osrs/runelite/files/4014201/jvm_crash_pid_17164.log)

**Comment by xKylee** [comment]
Looks like a memory problem judging by the thread. Does it happen every time you to go zmi, or only this one instance?

**Comment by Gamer1120** [comment]
It happens randomly, I think about 2-3 times per week, however, this is the third time it happened today. During the third time, I was updating my GPU driver. I posted my logs of the second time it happened (1-2 month old driver).

I also see that I'm not yet fully sober, as I was not doing ZMI, but was runecrafting in Zeah. I've been doing that for the past week or so and expect to do the same in the coming week or so.

**Comment by Lucwousin** [comment]
As far as I know this isn't something we can really do anything about, as it's a jvm bug and definitely out of my league to fix.

**Comment by stone-wall** [comment]
i'm pretty confident that this is a bug with joogl/opengl, or maybe even something on jagex's end as this has been happening a lot more frequently in the past week/2. loads of runelite users are getting the same crashes/issues
