### ISSUE TITLE
Zulrah Helper Doesn't Know What To Do After Jad Phase

### ISSUE THREAD

**Issue by XJ-1** [open-osrs/runelite#2189]
**Describe the bug**
Once you reach a Jad Phase at Zulrah the plugin tells you to stand in wrong spots, stops telling you what to pray and in general is very unreliable. Side Bug: Sometimes it just doesn't tell you to swap at all when it is needed Pre-Jad Phase but its rare. Unsure how to reproduce that last issue.

**To Reproduce**
1. Go to Zulrah and reach the Jad Phase.
2. Be Confused.
3. Don't die before getting to Jad by the rare occasion that the plugin doesn't tell you to swap to range after a mage phase.

**Expected behavior**
I expect it to behave like it would as if you just entered zulrah.

**Environment (please complete the following information):**
Windows
All latest releases, made sure to update everything together with Jim.

**Comment by xKylee** [comment]
this is no longer a openosrs supported plugin.
