### ISSUE TITLE
raids: incorrect layout detected

### ISSUE THREAD

**Issue by SRLJustin** [open-osrs/runelite#2203]
Raids scouter is reporting incorrect layouts

https://i.imgur.com/fwYWwsb.png

Top message from Clan Chat (They are using vanilla RL)

Second message is the message sent from OpenOSRS failing to detect Tekton room and Mutttadiles room.

**Comment by emiljensen2** [comment]
This should get fixed with https://github.com/open-osrs/runelite/pull/2201

**Comment by stone-wall** [comment]
ill close this if anyone can test and confirm it was fixed

**Comment by SRLJustin** [comment]
nightly scout raider looks fixed
