### ISSUE TITLE
Show indicators over players risking over a certain value in items

### ISSUE THREAD

**Issue by sobes-sudo** [open-osrs/runelite#2209]
This stems from a discussion had in the discord. Exilent currently has a feature where it indicates when players are risking over certain value and shows it an old school bounty hunter skull.

Read about it here: https://exilent.org/wiki/Loot_sniper

Apparently the value is already being calculated in some other spots, so I was told it shouldn't be too hard to implement this.

**Comment by xKylee** [comment]
this would go against Jagex's statement, mainly being "offers additional information about other players, with the purpose of scouting pvp targets"
