### ISSUE TITLE
Nylocas count sometimes goes multiline

### ISSUE THREAD

**Issue by ThatGamerBlue** [open-osrs/runelite#2220]
**Describe the bug**

**To Reproduce**
1. Go to ToB
2. Get to nylocas without planking
3. See this: https://i.imgur.com/MXHt0Zb.png
4. Ree

**Expected behavior**
It stays on the same line

**Screenshots**
https://i.imgur.com/MXHt0Zb.png

**Comment by xKylee** [comment]
this is no longer a openosrs supported plugin.
