### ISSUE TITLE
Microstuttering during Chambers of Xerics still occuring

### ISSUE THREAD

**Issue by bugrs** [open-osrs/runelite#2262]
The past week I have been experiencing intense microstuttering and lag at chambers of xeric and the only solution has been to restart client which is incredibly frustrating to do during a solo. The lag is unbearable and isn't fixed by any toggling of plugins or chambers related plugins.

This issue only occurs at Chambers of Xeric. I have not had the GPU plugin enabled at any point. 

Attached is a gif detailing the stutter and lag. 
https://i.imgur.com/4BNzZZA.gifv

**Comment by xKylee** [comment]
Please ensure you are using the right java version and java is uptodate. If it is, please also try adoptopenjdk. Both of these have resolved this issue in the past for other users
