### ISSUE TITLE
Plugin enable/disable buttons do not sync when toggled from within plugin's config menu

### ISSUE THREAD

**Issue by dutta64** [open-osrs/runelite#2269]
**Describe the bug**

Toggling a plugin on or off from within the plugin's settings menu does not toggle the button from the main menu.

**To Reproduce**

1. Open the Plugin/Configuration menu
2. Click the 'Edit plugin configuration' cog wheel button for any plugin
3. Click the 'Enable/Disable plugin' blue slider button to enable/disabled the plugin.
4. Click the '<' arrow to back out to the menu
5. Observe that the 'Enable/Disable plugin' blue slider button in the main menu did not update

**Expected behavior**

Enable or disabling a plugin from within its respective configuration menu should update the button in the global menu.

**Environment:**

OpenOsrs Nightly

**Comment by Owain94** [comment]
Hmm i might've introduced this bug with the config rework, I'll take a look at it later today

**Comment by xKylee** [comment]
@Owain94 is this now resolved?
