### ISSUE TITLE
"Increased performance mode" in the stretched mode plugin broken.

### ISSUE THREAD

**Issue by xHous** [open-osrs/runelite#2271]
The plugin isn't working at all, this is how it looks currently https://i.imgur.com/CVneJvG.gif, and this is how it is suppose to look https://i.imgur.com/ieJghJ3.gif.

**Comment by Owain94** [comment]
Fixed in https://github.com/open-osrs/plugins/commit/4c97f4468f439127105b61d6d54f49c8db4be969
