### ISSUE TITLE
Crash when using the 'Floating' or 'Fullscreen' map in the Brimhaven Dungeon.

### ISSUE THREAD

**Issue by TomMartow** [open-osrs/runelite#2334]
**Describe the bug**
The client crashes when you open the floating or fullscreen map in the Brimhaven Dungeon, this does not happen when using the instance map.

**To Reproduce**
1. Open Floating or Fullscreen map in the Brimhaven Dungeon.

**Expected behavior**
You are supposed to be able to read the map, unfortunately due to this bug, I am unable to navigate the dungeon and have died multiple times. This is not acceptable and I want my 10 tbows back.

**Screenshots**
**https://gfycat.com/BlackandwhiteRipeBird**

**Environment (please complete the following information):**
Windows 10

**Additional context**
[client.log](https://github.com/open-osrs/runelite/files/4188868/client.log)
[launcher.log](https://github.com/open-osrs/runelite/files/4188870/launcher.log)

**Comment by xKylee** [comment]
this should be resolved, can you try again @TomMartow

**Comment by TomMartow** [comment]
Yes, this has been fixed and can be closed.
