### ISSUE TITLE
Consistent GPU-plugin crashed

### ISSUE THREAD

**Issue by danwong** [open-osrs/runelite#2338]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
While Raiding (Chambers of Xerics, or Theatre of Blood) and just miscellaneous things in the game, my client will crash. It often hangs the entire system and makes other apps frozen. I usually have to restart my pc.

**To Reproduce**
Generally, it doesn't happen immediately, it can take a few hours of gameplay and is unpredictable but it will crash. It seems to be an issue with the swap buffers method. It seems that the method on line 1121 is deprecated. https://i.imgur.com/6SoILEA.png

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - the most updated version of windows and oprs.

**Additional context**

```
2020-01-29 22:08:43 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
com.jogamp.opengl.GLException: Error swapping buffers
	at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
	at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1121)
	at bf.xh(bf.java:14168)
	at bf.vn(bf.java)
	at bf.run(bf.java:328)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It generally shows as a hardware crash in Windows Reliability monitor. 
Hardware: Nvidia 2080 super. I got a replacement one as well to ensure it wasn't the hardware.
Also, I replaced the ram and alas, the issue was still persistent.

**Comment by ThatGamerBlue** [comment]
fixed
