### ISSUE TITLE
Drop party plugin not working

### ISSUE THREAD

**Issue by Iron-Wealth** [open-osrs/runelite#2341]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
no paths being shown for the dropping player. The plugin was working fine for me before the customizable plugin client

**To Reproduce**
1. Go to the Drop Party plugin
2. Add a player to the dropping player
3. It won't show the path the dropping player has walked.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by xKylee** [comment]
this is no an openosrs supported plugin.
