### ISSUE TITLE
Cannon plugin not working for last few days

### ISSUE THREAD

**Issue by letthiswork1** [open-osrs/runelite#2343]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
Cannon plugin not tracking ammo

**To Reproduce**

**Expected behavior**
Cannon plugin should show a counter on the cannon and in the moveable area

**Screenshots**
Tracker just shows 0 balls

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS] Windows 10
 - RuneLite version: [e.g 1.4.6] Lest versions
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Owain94** [comment]
Fixed

**Comment by letthiswork1** [comment]
confirmed ty
