### ISSUE TITLE
Cannon Plugin Showing Nonexistent Cannon(Phantom Cannon?)

### ISSUE THREAD

**Issue by kames1** [open-osrs/runelite#2370]
I'm gonna be honest, got distracted reading malware.wikia.com while banking during a smoke devil task, I got timed out, my cannon decayed. Reclaimed it and went back to the cave to... I think this screenshot will best describe the bug: https://i.imgur.com/uTlk1P2.png

Steps to Reproduce: 
Step 1: Setup Cannon
Step 2: Leave the area
Step 3: Let it break down and decay requiring it to be reclaimed at Nulodion(Can do like me get timed out reading malware.wikia.com pages for 3 hours)
Step 4: Reclaim cannon from Nulodion and go back to the area it was setup.

OS: Windows 10 Build 1909
Runelite version: 1.6.6-snapshot
OpenOSRS Launcher Version: 2.0.5
OpenOSRS Version: 3.0.3
OSRS Rev: Rev-188
Nothing in the logs I can see pertain to the issue. Can upload if needed.

**Comment by ThatGamerBlue** [comment]
Your client is way out of date, latest client is 3.0.4 and latest runelite is 1.6.7

**Comment by kames1** [comment]
Restarting client now. Gonna see if it's still there.  I could of swore I updated it this morning.
