### ISSUE TITLE
Client occasionally freezes when using teleports

### ISSUE THREAD

**Issue by Jawnb64** [open-osrs/runelite#2390]
**Describe the bug**
Sometimes when using any form of teleport (Jewlery/magic/fairy ring) the game window freezes and be comes unable to be interacted with. The client it self does not crash. 

**To Reproduce**
1. Play for a bit
2. Use a teleport
3, Client will sometimes freeze, not always

**Expected behavior**
Teleport should happen without incident

**Environment (please complete the following information):**
 - OS: Windows 10
 - OpenOSRS version: 3.0.6
 - Launcher version: 2.0.5

**Additional context**
Log from crash: 
[client.log](https://github.com/open-osrs/runelite/files/4269420/client.log)

**Comment by redeems** [comment]
This looks to be caused by an external plugin. Please disable them all, and report back if the issue continues to happen with them disabled. I was not able to reproduce the error.
