### ISSUE TITLE
RL menu entry swapper has a shift wear/wield method in bank interface

### ISSUE THREAD

**Issue by Eelpan** [open-osrs/runelite#2393]
I think title says it all :) 
I runelite there is a feature in "Bank Deposit Shift-Click" where you can Choose "Eat/Wield/Etc". from a dropdown. 
really nicefor gearing up in bank, missing it in openOsrs.

Love the client btw! :)

**Comment by xKylee** [comment]
It isn’t missing, we have this under hotkey swapping.
