### ISSUE TITLE
runeliteplus.properties symlink get overwritten

### ISSUE THREAD

**Issue by whs** [open-osrs/runelite#2411]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
I sync runeliteplus.properties between machines using Syncthing. The file is symlinked to a syncthing-managed folder. After the plugin manager was released the symlink always get replaced by a real file.

**To Reproduce**
1. Replace runeliteplus.properties by a symlink
2. Start the launcher
3. Play the game
4. Quit the launcher
5. Observe that runeliteplus.properties is not a symlink

**Expected behavior**
runeliteplus.properties should always remain a symlink

**Environment (please complete the following information):**
 - OS: Arch Linux and macOS
 - OpenOSRS version: 3.0.7
 - Launcher version: 2.0.5

**Comment by ThatGamerBlue** [comment]
Stupid bot...

**Comment by Lucwousin** [comment]
You could make it read only? Feel like that may still be unwanted as it would stop saving settings

**Comment by Lucwousin** [comment]
For now a dirty "fix" would be to use the --config run arg to directly link to the config file, but using .getCanonicalPath would also solve this issue and seems like the better solution
