### ISSUE TITLE
Demonic gorilla plugin not working

### ISSUE THREAD

**Issue by Eelpan** [open-osrs/runelite#2412]
Bug:
The attack style that the demonic gorillas use, is not showed above their overhead prayers.
Turning plugin off then on makes it appear, but it does not have the counter, and does not update when the gorilla changes attack style.

1. Go to Demonic gorillas with plugin enabled
2. Disable and enable it, to make attack style appear
3. Counter and attack style does not update when npc changes.

Expected behavior:
Plugin works, like last week when i used it :) 

Environment:
 - OS: Windows
 - OpenOSRS version: [e.g 3.0.7]
 - Launcher version: [e.g 2.0.5]

**Comment by Eelpan** [comment]
Any reply so i know why this is invalid? :O

**Comment by Ganom** [comment]
We don't offer this plugin, thats why its invalid.
