### ISSUE TITLE
Alchemical Hydra Plug

### ISSUE THREAD

**Issue by reapper57** [open-osrs/runelite#2429]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
The plugin is not working at all. It does not show what to pray or safe spots for poison. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - OpenOSRS version: [e.g 3.0.3]
 - Launcher version: [e.g 2.0.4]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by xKylee** [comment]
Plugin isn’t supported
