### ISSUE TITLE
Alchemical Hydra plugin Broken

### ISSUE THREAD

**Issue by reapper57** [open-osrs/runelite#2430]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
Alchemical Hydra plugin broken

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - OpenOSRS version: [e.g 3.0.3]
 - Launcher version: [e.g 2.0.4]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by xKylee** [comment]
Plugin was removed, isn’t supported, won’t be updated.
