### ISSUE TITLE
discord party pinging broken

### ISSUE THREAD

**Issue by emiljensen2** [open-osrs/runelite#2443]
**Describe the bug**
When in a party pinging doesn't ping/show

**To Reproduce**
Join discord party with other openosrs user.
Hold shift and you'll see you won't walk, but no pings are happening. 

**Expected behavior**
No pings show, despite not walking when pressing with shift held in.

**Screenshots**

**Environment (please complete the following information):**
windows 10

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by ThatGamerBlue** [comment]
Somewhat related to #2289
