### ISSUE TITLE
Cannot create generalised subclass of Plugin

### ISSUE THREAD

**Issue by stevebasher** [open-osrs/runelite#2531]
https://github.com/open-osrs/runelite/blob/4df96086b520868dae60f27a51994c7be28a864d/runelite-client/src/main/java/net/runelite/client/plugins/ExternalPluginManager.java#L652

This line means the direct superclass of your plugin *must* be Plugin. This stops you creating a base class for a set of plugins (which itself extends Plugin) and extending from that base class, allowing a much cleaner codebase for a multi-plugin project.

Can we change it to `!Plugin.class.isAssignableFrom(clazz)`? Or even remove it as due to #639 `Class<? extends Plugin> clazz = plugin.getClass();` clazz is guaranteed to extend Plugin anyway?

If not, why do we care if that the custom plugin class is a direct extension of the vanilla Plugin class?

**Comment by Ganom** [comment]
This is a remanent from the legacy external loader, I agree this should be changed.

**Comment by Ganom** [comment]
Fixed by #2532
