### ISSUE TITLE
Tmorph: attempting different "class" tmorphs such as helmets to crowns (head invisible) or wands to staffs (weapon invisible) don't work. Lack of info in the tmorph plugin about weapon/armor "families" or bug?

### ISSUE THREAD

**Issue by GrimWrath** [open-osrs/runelite#2551]
When attempting to tmorph any helmet into a crystal crown, the players head becomes invisible. Tested with void range helm and nezzy faceguard, along with every color crystal crown.

The tmorph _does_ work with party hats and the like. 

Similarly, a kodai wand tmorph into a zuriel staff will cause the weapon to become invisible, but using an apprentice wand will work.

Adding info about weapon/armor families would avoid confusion about this. Ie. Wands/Crowns/Helms

Or it is a bug. Not sure.

**Comment by redeems** [comment]
This seems like a support question more than a bug. Will look into it to be sure, however if you need help, the discord would be the place to go.
