### ISSUE TITLE
Blackjack tool

### ISSUE THREAD

**Issue by Seely03** [open-osrs/runelite#2565]
The option remains on knockout even when the bandit is unconscious.

Go to Pollnivneach and left click to blackjack a bandit. Even when knocked out the option is still knockout and not pickpocket. as opposed to becoming pickpocket when the bandit is unconscious.

This is on the most recent version of the client.

I've tried restarting the client, disabling the menu entry stopper and turning the plugin on and off but none of these had an effect.

**Comment by xKylee** [comment]
Not our plugin.
