### ISSUE TITLE
Loading screen stuck at "Loading internal plugins 7 / 7"

### ISSUE THREAD

**Issue by SGQ12** [open-osrs/runelite#2573]
^
Windows

**Comment by xKylee** [comment]
there's a support channel for a reason chief.

**Comment by SGQ12** [comment]
That's the first place I went, chief.
The help I got didn't work.

**Comment by zeruth** [comment]
Getting smart with the dev isn't an appropriate response. Either way, you created an issue that is very vague, without any kind of supporting information. Bet you it would have worked had you cleared .runelite. Bad issue with a bad attitude, it will be your last.
