### ISSUE TITLE
"Client always on top" randomly affects other windows too after some time

### ISSUE THREAD

**Issue by AndyDeany** [open-osrs/runelite#2609]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
Enabling "Client always on top" randomly makes other windows always on top as well.

**To Reproduce**
1. Go to Configuration->System->RuneLite and click the cog. Under Miscellaneous, ensure the tickbox "Enable client always on top" is ticked.
2. Have the client open for a while, maybe tab in and out of it every so often. (I will update this if I figure out a surefire way to cause this to happen).
3. Eventually, random other open windows that have also been open a while will start to be marked as "always on top" and will take priority over other windows. It doesn't seem any type of window is immune to this. I've definitely seen it happen with Chrome, Discord and Git Bash. Probably others too but I don't remember right now.

**Expected behavior**
Other windows should not randomly become "Always on top", requiring them to be closed and reopened to fix it (until it happens again).

**Environment (please complete the following information):**
 - OS: Windows 7 Professional SP1
 - OpenOSRS version: 3.3.3 (has happened in the past with other versions too, for a long while)
 - Launcher version: 2.2.0

**Comment by xKylee** [comment]
there is absolutely 0 way that the client would affect anything outside of the client.

**Comment by xKylee** [comment]
there is absolutely 0 way that client config options such as enable ontop would affect programs or settings outside of the client. enabling always on top is contained to the java frame of the client and the client only.

**Comment by AndyDeany** [comment]
This has happened to me so many times, and _only_ when I have OpenOSRS open, to such a statistically significant degree that I would say there's a 99.9%+ chance that they're connected. I will update when I find a way to reproduce this reliably. The level of coincidence for this not to be the case would be absurd. I don't know much Java, but I would urge you to reconsider your position on it being impossible. I can understand that perhaps it is outside of your control and is a problem with Java itself, but I'm adamant that having the client open is causing it.

There's also a chance that it has nothing to do with the "Enable client always on top" option, and all that is required is for the client to be open, but that seems even more unlikely. If I find a way to reproduce it then I will test it without the option enabled.
