### ISSUE TITLE
Screenshot plugin - Include overlays not working

### ISSUE THREAD

**Issue by Tdarnell** [open-osrs/runelite#2653]
Toggling off the "Include overlays" option doesn't hide the Open-OSRS overlays in the chambers of xeric (untested elsewhere), they visibly disappear for a second but are still included in the final screenshot. Potentially a delay issue?

My suggestion would be to toggle off the overlays for slightly longer to ensure they're not captured in the screenshot.

**Comment by Lucwousin** [comment]
feel like this may have to do with the new mirror overlay level

**Comment by zeruth** [comment]
Yeah I don't think so. This occurs even without gpu. 

The software side of mirror is beyond trivial. Seems like it has to do with the following snippet in ScreenshotPlugin
```
		if (!config.includeOverlays())
		{
			overlayRenderer.setShouldRender(false);
		}

		Consumer<Image> imageCallback = (img) ->
		{
			// This callback is on the game thread, move to executor thread
			executor.submit(() -> takeScreenshot(fileName, subdirectory, img));
		};```

I created my own event which draws the AFTER_MIRROR layer only after all other draws are done, and sends that image to be drawn on an entirely separate canvas with the final layer. I dont modify other draw calls at all. Seems to be there is a problem with the callback:

```
		if (!config.includeOverlays())
		{
			overlayRenderer.setShouldRender(false);
		}

		Consumer<Image> imageCallback = (img) ->
		{
			// This callback is on the game thread, move to executor thread
			executor.submit(() -> takeScreenshot(fileName, subdirectory, img));
		};```

The game canvas indeed disables overlays but this callback still returns "tainted" overlay screenshots.

https://github.com/open-osrs/runelite/blob/fe961d6fd1d9496c5f2c5d411d3b9bf1258ee8cf/runelite-client/src/main/java/net/runelite/client/callback/Hooks.java#L408
All the mirror overlay does in software mode is this:
```
		if (client.isMirrored())
		{
			drawFinishedEvent.image = copy(finalImage);
			drawFinishedEvent.image.getGraphics().drawImage(cursor, mouseX, mouseY, null);
			eventBus.post(DrawFinished.class, drawFinishedEvent);
		}

		try
		{
			renderer.render((Graphics2D)finalImage.getGraphics(), OverlayLayer.AFTER_MIRROR);
		}
		catch (Exception ex)
		{
			log.warn("Error during post-mirror rendering", ex);
		}```

There is absolutely no way that has to do with mirror.

**Comment by Tdarnell** [comment]
This issue is still active

**Comment by alicexin** [comment]
I found if you add a small delay after the overlayRenderer.setShouldRender(false); in the methods with the signatures:
takeScreenshot(String fileName, String subdirectory)
takeScreenshot(String fileName)

it helps. obviously not a real fix but thought i'd share this info in case anyone plans to look into what the real fix should be / the root cause
