### ISSUE TITLE
A problem occurred configuring root project 'OpenOSRS'.

### ISSUE THREAD

**Issue by jboyken3** [open-osrs/runelite#2747]
**Describe the bug**
trying to follow https://github.com/open-osrs/runelite/wiki/Building-with-IntelliJ-IDEA but error occurs

**To Reproduce**
Error occurs as soon as I start an IntelliJ project cloning this github.

**Expected behavior**
Happens as soon 

**Screenshots**
![image](https://user-images.githubusercontent.com/58668784/87757678-07bed900-c7d9-11ea-985a-1e0a060bc112.png)

**Environment (please complete the following information):**
 - OS: Windows 10

**Additional context**A problem occurred configuring root project 'OpenOSRS'.
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by xKylee** [comment]
you will need to use java 11, not java 8.
