### ISSUE TITLE
Unable to bind mouse4 and upwards

### ISSUE THREAD

**Issue by Speedy2662** [open-osrs/runelite#2790]
**Describe the bug**
Plugins do not allow me to bind additional mouse buttons (mouse4 and upwards)

**To Reproduce**
1. Go to a plugin with a bind
2. Try to bind the hotkey to a mouse button

**Expected behavior**
MOUSE4 should appear and let you use the button to perform the hotkey.

**Environment (please complete the following information):**
 - OS: Windows 10
 - OpenOSRS version: 3.4.3
 - Launcher version: 3.4.3

**Additional context**
Under 'Runelite' I have 'Block Extra Mouse Buttons' disabled. This setting makes no difference to me.

**Comment by xKylee** [comment]
Happens in rl too. Likely to be fixed upstream
