### ISSUE TITLE
wiki: Creating new plugins tutorial requires an update

### ISSUE THREAD

**Issue by Galtiak** [open-osrs/runelite#2799]
**Describe the bug**
1. Down the test folder from https://github.com/open-osrs/example-external-plugin.
There isn't a test folder at this page.

**To Reproduce**
1. Go to https://github.com/open-osrs/example-external-plugin.
2. Look for test folder.

**Expected behavior**
A test folder that is going to be used in that tutorial.

**Comment by xKylee** [comment]
Instead of “test” use javaexample
