### ISSUE TITLE
BZIPDecompression (NegativeArraySizeException

### ISSUE THREAD

**Issue by Arthur-IO** [open-osrs/runelite#2949]
Using the Gradle task rsc-run results in a NegativeArraySizeException

**To Reproduce**
Run the rsc-rune gradle task

**Expected behavior**
Client should run without a crash.

**Screenshots**
![](https://i.gyazo.com/b561c59352578d8ed9361919139a260b.png)

**Comment by ThatGamerBlue** [comment]
fixed in 563587e6
