### ISSUE TITLE
openosrs folder and files are defaulted to read perms only

### ISSUE THREAD

**Issue by Bee-Ar** [open-osrs/runelite#2960]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
openosrs folder and files are defaulted to read only, causing client restarts to clear settings/plugins, not sure if this is happening on macOs/linux

**To Reproduce**
1. install client
2. check permissions on USER/.openosrs

**Expected behavior**
should default to full perms (read/write/del) at user level

**Environment (please complete the following information):**
- could reproduce on windows 10

**Comment by Hoodz** [comment]
Does this also happen when you run the client as admin?
