### ISSUE TITLE
Plugin Hotswap not working properly

### ISSUE THREAD

**Issue by rokaHakor** [open-osrs/runelite#2965]
Following this guide but for my own personal plugins. The hotswap worked fine before 4.0.0.
https://github.com/open-osrs/runelite/wiki/Building-the-plugins-with-IntelliJ-IDEA

Steps to Reproduce:
1. Build the plugins using gradle with the "build copyDeps publishToMavenLocal" tasks.
2. Then run the client using gradle with PLUGIN_DEVELOPMENT_PATH set to my plugin folder path.
3. Client launches and my plugins show up and work fine.
4. Make changes to a plugin in IntelliJ and rebuild the plugins again.
5. Stop the plugin then use the hotswap button in the plugin list for the plugin that I modified.
6. The new version does not load up, its still the previous version. (made sure by having startUp() log some text and modifying the text)
7. However if I use the hotswap button while the plugin is enabled then it loads up the new version.
8. Stop the plugin then enable it again then it goes back to the previous version.

Expected behavior:
The client should load the latest built version of the plugin when the hotswap button is hit.

**Comment by egertaia** [comment]
As my PR got merged this issue can be closed.

**Comment by rokaHakor** [comment]
The issue is still not fixed.

**Comment by egertaia** [comment]
I'll recheck this soon. I've tested it on sidebar level not startup. The version number updated. So that's why I thought it works.

**Comment by egertaia** [comment]
@rokaHakor is correct. Id does update the sidepanel information (f.e. you change the version number) but it indeed doesnt swap the jar to correct one.
I'll recheck this asap.

**Comment by rokaHakor** [comment]
I still can't figure out whats causing this bug lol. It seems as though the client is caching the plugins and when to start a plugin it runs the old cached version even if you pressed the hotswap button where it should update the cached plugins.
