### ISSUE TITLE
Cox Timers Broken (But works on Runelite?)

### ISSUE THREAD

**Issue by Jamonnin3** [open-osrs/runelite#2970]
![image](https://user-images.githubusercontent.com/22843757/110726908-43833480-81e8-11eb-99b7-6065aab7c8f0.png)

It looks like the above and does weird things in chat like tons of duplicate annoying lines when it should look like this:

![image](https://user-images.githubusercontent.com/22843757/110726966-61e93000-81e8-11eb-9136-6342b75aafe6.png)

It's from the plugin hub

![image](https://user-images.githubusercontent.com/22843757/110726997-73323c80-81e8-11eb-9877-948bca8bd49f.png)

**Comment by ReeeMan** [comment]
for some reason on runelite 
  @Subscribe
  public void onGameObjectDespawned(GameObjectDespawned e) {
    if (e.getGameObject().getId() == ObjectID.LARGE_HOLE_29881) {
      splitphase();
      olm_phase = ~olm_phase;
    }
  }
  
  this only triggers once.
  
  but on OPRS it triggers 20+ times 1 chat message for each time as seen in the screenshot.
  
  is this something to do with OPRS tracking dynamic objects or something?

**Comment by ThatGamerBlue** [comment]
can you test this build of oprs for me? https://www.thatgamerblue.com/oprs/oprs-20210312-01.jar

**Comment by Jamonnin3** [comment]
> 
> 
> can you test this build of oprs for me? https://www.thatgamerblue.com/oprs/oprs-20210312-01.jar

Speaking to me? Sorry not sure if this is being focused on or not but it ruins a pretty important plugin for raiding. Just wanted to see if there's been any progress or if there will be any in the future, thanks :)
