### ISSUE TITLE
my client is not working

### ISSUE THREAD

**Issue by mikeyyyyyyyyyy** [open-osrs/runelite#3093]
when i tried to launch my open orsrs client it provides me with this error 

![image](https://user-images.githubusercontent.com/96280598/146496694-79fbd5dd-b51b-48e9-a599-90d471a2e368.png)

**Comment by Failed4life** [comment]
One or more of your externals are broken causing the error. Remove the broken plugin(s) from the .openosrs\plugins folder

**Comment by mikeyyyyyyyyyy** [comment]
> 

how do i know which plugin is broken ?? i never had this concern

**Comment by Failed4life** [comment]
You can easily disable all externals just by renaming the plugins folder temporarily and then rename it back to "plugins" when the broken plugin(s) are fixed

Windows: %userprofile%\.openosrs
Mac: $HOME/.openosrs
Linux AppImage: ~/.openosrs
Linux Snap: /snap/openosrs/common/.openosrs

Mac/linux users: The .openosrs folder is hidden by default, you may have to unhide it.
On mac you can use the following key combination to show hidden folders/files:
CMD + SHIFT + .

**Comment by mikeyyyyyyyyyy** [comment]
can you please guide me on how to access this folder i am sorry mate having abit of trouble locating it

**Comment by mikeyyyyyyyyyy** [comment]
i am using windows
