### ISSUE TITLE
runescape-client can't work

### ISSUE THREAD

**Issue by chenp2018** [open-osrs/runelite#3128]
**Describe the bug**
can't login the account successfully throught  the runescape-client when updated to rev 203.

**To Reproduce**
when login the account throught the runescape-client, it always prompt “Runescape has been updated! please reload this page.”

**Screenshots**
![20220210233208](https://user-images.githubusercontent.com/49015079/153442447-93a7fa52-2fee-49af-99d9-f3f2a95a8a14.png)

**Comment by Owain94** [comment]
Update and build again, also this is not a support forum

**Comment by ThatGamerBlue** [comment]
fixed in 331ecb5da7a251929abf9b280a02e2ffe2959d27
