### ISSUE TITLE
GIM Chat commands

### ISSUE THREAD

**Issue by justingerolami** [open-osrs/runelite#3137]
**Describe the bug**
Chat commands in the GIM chat do not work. They work in all other situations. Chat commands work on Runelite in GIM chat. My own investigation found that there is a pipe "|" transmitted in front of GIM messages. For example, "|hello" or in the case of a command, "|!qp". This prevents the chat command plugin from properly working in GIM chat. 

After forcing the message in OnChatMessage() in chat command plugin to remove the "|" the commands work as intended. 

**To Reproduce**
Simply try to execute a chat command in a GIM chat. 

**Expected behavior**
The chat commands should produce a response. 

**Environment (please complete the following information):**
 - OS: macOS
 - OpenOSRS version: 4.20.2

**Additional context**
Sample of GIM chats from logs, OpenOSRS
1. [Client] DEBUG injected-client - Chat message type CLAN_CHAT: |Test
2. [Client] DEBUG injected-client - Chat message type CLAN_CHAT: |!Total

Sample of GIM chat from logs, Runelite
1. [Client] DEBUG client-patch - Chat message type CLAN_GIM_CHAT: Test
2. [Client] DEBUG client-patch - Chat message type CLAN_GIM_CHAT: !Total

**Comment by SRLJustin** [comment]
fixed in https://github.com/open-osrs/runelite/pull/3139
