### ISSUE TITLE
publish time tracking/timer to configurable external service

### ISSUE THREAD

**Issue by jdavisclark** [open-osrs/runelite#3200]
**Is your feature request related to a problem? Please describe.**
There's lots of daily or multiple per day activities on timers in OSRS. Runelite already has great time tracking for most/all of these built in, but no good way to get reminders to your phone/smart-watch/etc...

**Describe the solution you'd like**
I'd like a way to opt-in to publishing data from the time-tracking plugin to a 3rd party service, to facilitate getting access to that data for push notifications to mobile phones/watches/etc... The exact external service is TDB, but I'd like the outgoing request to be somewhat configurable to support, e.g., IFTT webhooks as well as any custom service someone wants to develop (which I'd likely do, and maybe host for free for others in the future).

**Describe alternatives you've considered**
There *may* have been round-about ways to do this by enabling desktop notifications from the time tracking plugin, and then using certain Microsoft/Apple apps to forward desktop notifications to your phone. But at least the microsoft version of this appears to be dead now. 

**Additional context**
I'd potentially be willing to contribute this to the main time-tracking plugin, or as an additional plugin. For starters I'm just looking to see if its something that you guys would formally accept.

Thanks!

**Comment by Owain94** [comment]
This data is saved to the config, it can easily be extracted by an external plugin if you want to do anything with it, it doesn't have to be build into the in client timer tracking plugin

**Comment by jdavisclark** [comment]
I figured. Would a plugin that consumes that and published it to a configurable external service be kosher to make it in to the official plugin catalog?
