### ISSUE TITLE
Periodic Random Java Crashes 

### ISSUE THREAD

**Issue by DakotaJTS** [open-osrs/runelite#3209]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000012a895fba51, pid=13812, tid=7712
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001de3083d4b8, pid=2300, tid=6704
These are from just two of the many Java crash logs. each one has different pc, pid and tid numbers

Basically anywhere between 5 minutes and 120 minutes, my client will just shut off. There seems to be no discernable way to recreate it. There is no warning, one second I will be skilling or killing a monster, and the next my client will have closed, now popup or anything. I have uninstalled and reinstalled windows 10, Java and the OpenOSRS and Runelite clients but this bug persists. It also happens on the normal Runelite client at the same frequency. 

**To Reproduce**
I cannot find a reliable way to reproduce this bug. 

**Expected behavior**
When it does happen, the whole client just crashes and logs a crash. 

**Environment (please complete the following information):**
 - OS: Windows 10 64-bit 
 - OpenOSRS version: [4.28.0]
 - Launcher version: [3.0.0]

CRASH LOGS

[jvm_crash_pid_13812.log](https://github.com/open-osrs/runelite/files/8803757/jvm_crash_pid_13812.log)
[jvm_crash_pid_2300.log](https://github.com/open-osrs/runelite/files/8803777/jvm_crash_pid_2300.log)
[jvm_crash_pid_4236.log](https://github.com/open-osrs/runelite/files/8803780/jvm_crash_pid_4236.log)

Any and all help resolving this bug is greatly appreciated

**Comment by SRLJustin** [comment]
"It also happens on the normal Runelite client at the same frequency."

Not a OpenOSRS issue. This is why it was closed.
