### ISSUE TITLE
M1 macOS Monterey seeing `java.lang.IllegalStateException`

### ISSUE THREAD

**Issue by Olshansk** [open-osrs/runelite#3231]
**Describe the bug**

Using the `.dmg` from runescape.com, I cannot run the OSRS client on an M1 mac.

**To Reproduce**
1. Download Java for macOS from https://www.java.com/en/download/apple.jsp
2. Download OSRS from https://oldschool.runescape.com/download?client=failed
3. Run `open -o /tmp/rune /Applications/Old\ School\ RuneScape.app`

**Expected behaviour**
OSRS opens and is playable.

**Screenshots**
<img width="1608" alt="Screen Shot 2022-11-05 at 12 35 35 PM" src="https://user-images.githubusercontent.com/1892194/200137998-4a80419c-68e7-4487-935a-c07853200cbd.png">

**Environment (please complete the following information):**
 - OS: Apple M1 Macbook running macOS Monterary Version 12.5
 - OpenOSRS version: ???
 - Launcher version: ???

**Comment by Owain94** [comment]
Huh?

You're reporting an issue with the official jagex OSRS app to this outdated project?
