### ISSUE TITLE
Ability to hide individual plugins

### ISSUE THREAD

**Issue by farhan1666** [open-osrs/runelite#413]
**Is your feature request related to a problem? Please describe.**
The plugin tab is incredibly crowded at the moment, the average RL+ user doesn't need to edit the config for an API they don't use, or 4 different prayer hiding plugins, or Tarn's Lair shortcut highlighting, whilst these features are useful to have in the client it doesn't make sense for every single person to be able to see them all the time.

**Describe the solution you'd like**
Next to the Star icon on plugins have another button that instead marks plugins as hidden, when a plugin is marked as hidden it can either be sent to the bottom, or be hidden altogether, what happens would be determined by a config option in Plugin Organiser

**Describe alternatives you've considered**
Whilst far more complicated an arguably more professional and long term convenient solution would be to have an installer of sorts for the client where users could hand pick which plugins they would like, and the plugins they didn't pick would be hidden at runtime, though this is entirely unnecessary as clicking a button on each plugin users don't want is much simpler

**Additional context**
N/A

**Comment by Ganom** [comment]
Agree, this would be a good feature to have.
