### ISSUE TITLE
Verzik P2 Blue Ball Timer/Verzik Auto Counter

### ISSUE THREAD

**Issue by lolKai** [open-osrs/runelite#484]
If possible, would be pretty helpful in duos if a Verzik auto counter that counts up to 5 was added since the blue ball comes every 5 autos, or a timer that is the same duration as 5 autos so we know what auto the blue ball is coming.

**Comment by Ganom** [comment]
Very easy to add, i just need the animation for the attacks that count, and other info related to it.

**Comment by Ganom** [comment]
Still need the info for this.

**Comment by Kyleeld** [comment]
as above, do you have the animation for the attacks etc?
