### ISSUE TITLE
Ground items on CTRL

### ISSUE THREAD

**Issue by ZebGasm** [open-osrs/runelite#518]
its anoying when i have my loot show up when i press ALT i would like to have it on CTRL maybe you could make it remapable thx for ur time

**Comment by Kyleeld** [comment]
this can be done via the remapping keys plugin.

**Comment by pklite** [comment]
![image](https://user-images.githubusercontent.com/46624825/62278040-4ebf8d00-b415-11e9-8466-dbd23dfd71e6.png)
key remapping wouldn't help in this situation though
