### ISSUE TITLE
3t helper for skilling

### ISSUE THREAD

**Issue by Bryanrl** [open-osrs/runelite#622]
Plugin uses specific inventory spaces based on X, can be specific preset places or items in inventory marked as specific colors and has a marked square or squares and the plugin lights up the spaces based on a 3t rotation to help teach/promote consistency with 3t skilling

**Comment by Ganom** [comment]
Interesting idea, its definitely doable.

**Comment by JosephIaquinto** [comment]
FWIW I implemented a rudimentary system to do this with the inventory item outline colors https://github.com/JoeIaquinto/runelite/commit/42bdccb6ac4aa749988332f093e7ba478b5a2301
https://github.com/JoeIaquinto/runelite/commit/d21c1c2da251a17416147b4ed83408b8e9b13d8f
