### ISSUE TITLE
Pathing through NPC's when going to attack

### ISSUE THREAD

**Issue by lolKai** [open-osrs/runelite#625]
**Describe the bug**
Character will path towards the NPC you are clicking to attack, and will not attack. It mostly happens when im in p1 Verzik, shooting my staff specs at her. Instead of shooting the staff spec from the pillar it will give me a red click and path my character right up to Verzik and not shoot the staff auto. It has also happened to me on Bloat where ill click him and get a red click as if im going to auto him, but my character just paths through him.

**To Reproduce**
Can't really replicate it as it doesn't happen every time, and it happens very rarely. It happens most for me when using spec on P1 Verzik with Dawnbringer.

**Expected behavior**
Character attacks from range, or if melee, paths to NPC and attacks.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.3

I've seen some other people having this issue in the past when searching through the discord, seems rare though.
https://i.imgur.com/qQP5R4P.png

**Comment by Ganom** [comment]
@ThatGamerBlue

**Comment by ThatGamerBlue** [comment]
Note this is different from #613

**Comment by Lucwousin** [comment]
Feel like this may be #        9186

**Comment by Ganom** [comment]
Is this still an issue after the injector updates?

**Comment by xKylee** [comment]
can you confirm if this is still an issue in 2.1.4.0?

**Comment by f0rmatme** [comment]
@lolKai any update?

**Comment by tomcylke** [comment]
Don't quote me on this, but it feels like your mouse needs to hover over the npc for at least 1 frame before clicking otherwise this issue will happen. It occurs when you move your mouse extremely quickly (potentially with automation), or if you are experiencing severe fps drops.
