### ISSUE TITLE
Tag inventory items when they are useable

### ISSUE THREAD

**Issue by remigo** [open-osrs/runelite#648]
So this is mainly for alt accounts.
Would it be possible for items in your inventory to be tagged/marked as soon as they are ready to be used?

**For example: tag all sharks as soon as you are missing 20 hp & the same for prayer potions**

![image](https://user-images.githubusercontent.com/37721451/59682111-d048bc00-91d5-11e9-95ef-0e896817208d.png)

**Comment by lulwut** [comment]
As someone with a genuine medical condition that makes focusing on alts very difficult this would be great QOL. If it could even do more than highlight and actually just place a colour over the icon (opacity) that'd be great.
