### ISSUE TITLE
Tmorph enhancements

### ISSUE THREAD

**Issue by remigo** [open-osrs/runelite#662]
1. I know it's an experimental function but it would be great to have the option to swap more animations using tmorph.

2. The option to permanently change your npc using ::transform

**Comment by Ganom** [comment]
>     1. I know it's an experimental function but it would be great to have the option to swap more animations using tmorph.
> 
>     2. The option to permanently change your npc using ::transform

For 1. Would you want more animations to swap to the target animation, or more swaps and targets?
