### ISSUE TITLE
Supplies Tracker + Rune Pouch

### ISSUE THREAD

**Issue by Wornie** [open-osrs/runelite#775]
**Describe the bug**
Runes used from rune pouch are not added to Supplies Tracker

**To Reproduce**
1. Have Supplies Tracker Enabled.
2. Have Rune Pouch with Runes to cast a spell (in my case Entangle).
3. Cast the spell.
4. See that the runes are not added to the Supplies Tracker.

**Expected behavior**
Used runes to be added to the Supplies Tracker

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10 64-bit 1809 
 - RuneLite version: 1.5.28-SNAPSHOT
 - Launcher version: 2.0.1-1

**Additional context**
Found during a Barrows run, tested a few times to make sure. 
Logs with almost nothing in them below:
[client.log](https://github.com/runelite-extended/runelite/files/3336418/client.log)
[launcher.log](https://github.com/runelite-extended/runelite/files/3336419/launcher.log)

**Comment by f0rmatme** [comment]
https://github.com/runelite-extended/runelite/pull/912
fixed this i believe

**Comment by stantor42** [comment]
Using Vengence, and still does not track runes.
