### ISSUE TITLE
Wilderness line markers don't show in the revenant caves

### ISSUE THREAD

**Issue by Abi1024** [open-osrs/runelite#806]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The multiindicators plugin supports a feature that allows you to see lines that mark how deep an area of the wilderness is. These lines don't appear to work inside wilderness caves (specifically the revenant caves where this is most important).

**To Reproduce**
Enable multiindicators, go the revenant caves.  observe how the lines don't show in the caves.

**Expected behavior**
lines should show in the caves.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows

**Comment by Kyleeld** [comment]
they only show above ground for now.

**Comment by Lucwousin** [comment]
Maybe also #892?
