### ISSUE TITLE
Raids (COX) Suggestions

### ISSUE THREAD

**Issue by JackSparrow43** [open-osrs/runelite#813]
an overlay on ice demon, thieiving room boss, timer on vasa crystals, timer on muttadile at tree

- [ ] Ice demon - how many kindlings needed/left
- [ ] Thieiving room- how many grubs needed/left
- [ ] Timer on vasa crystals - total duration of time vasa has been at a crystal
- [ ] Timer on muttadile at tree - how long left before it begins attacking you again (if possible)

**Comment by farhan1666** [comment]
To the best of my knowledge the scaling formulas of 1 and 2 are not known and 4 is not possible or frankly even useful, 3 is nice for low DPS Vasa methods and should not be difficult

**Comment by JackSparrow43** [comment]
Can just do it for solo then, the plugin will state it is for solo only.
