### ISSUE TITLE
Disabling anti drag sets a custom cursor. 

### ISSUE THREAD

**Issue by ocekyled** [open-osrs/runelite#816]
**Describe the bug**
I'm using default mouse cursor normally and Dragon Scimitar when anti drag is enabled.
When turning off anti drag it sets the cursor to the selected custom cursor in the main custom cursor plugin, regardless of whether custom cursor is disabled.

**To Reproduce**
1. Disable Custom Cursor
2. Enable anti drag with cursor override
3. Disable anti drag

**Expected behavior**
Reset to default windows cursor if custom cursor is disabled.

**Screenshots**
![kyXcsTUK8l](https://user-images.githubusercontent.com/19616058/60385780-94aecb80-9acc-11e9-835f-cad051c7b180.gif)

**Comment by Hoodz** [comment]
I made a fix for this but its not merged. 
#574 Is the pr number, its declined because it would fail if the custom cursor plugin is still on.
