### ISSUE TITLE
Tick-eat timer for muttadiles

### ISSUE THREAD

**Issue by ThatGamerBlue** [open-osrs/runelite#883]
Tick-eat timer for muttadiles.
Needs projectile ids: slow range attack from the small one, fast mage attack from the small one and the same from the big ones. Melee I'm not too worried about because it's your own fault if you get chomped

**Comment by ThatGamerBlue** [comment]
Stale issue message

**Comment by Crystalknoct** [comment]
Muttadile:
Range- 7421
Eating tree - 7420
Mage- 7422
Stomp- 7424
Melee- 7420
Animation ids
