### ISSUE TITLE
Dynamic Overlay Font as "Bold" with font "Runescape" doesn't work

### ISSUE THREAD

**Issue by Spongled** [open-osrs/runelite#946]
**Describe the bug**
RuneLite+ doesn't seem to support or properly display the bold Runescape font on ground overlays.

Example - RL+ vs RL: https://imgur.com/a/NEChXMz

**To Reproduce**
Have font set to default (Runescape) on RL+ and select "Bold" as the Dynamic Overlay Font. Compare by dropping an item and observe the font in RL+ vs RL.

**Expected behavior**
RL+ should be showing a bold Runescape font on ground overlays.

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - RuneLite version: 1.5.29

**Comment by bigmemes420** [comment]
You can temp fix this by changing it to another option then back to bold

**Comment by Spongled** [comment]
Yeah it seems so. By the looks of things, the text is defaulting to "Small" before manually swapping it back to bold.

**Comment by f0rmatme** [comment]
https://github.com/runelite-extended/runelite/pull/1070
