### ISSUE TITLE
Some overlays vanishing in the wilderness

### ISSUE THREAD

**Issue by bigmemes420** [open-osrs/runelite#991]
**Describe the bug**
Some overlays (like boost information) seem to vanish ~29/30 wilderness line

**To Reproduce**
1. Go to 29/30 wildy line (specifically in rev caves for me)
2. walk around until the overlay disappears

**Expected behavior**
Overlays should show

**Screenshots**
https://media.nullcoreproject.net/i/7ec54e97.png (Overlays here work fine)
https://media.nullcoreproject.net/i/d98cd7f9.png (Overlays not working here)

**Comment by f0rmatme** [comment]
i've seen this issue while my friend was playing, after he toggled on overhead text for players his overlay vanished. i think its linked some how

**Comment by bigmemes420** [comment]
I feel this is due to showing attackable players in the wilderness as that seems to be when it happens in this case.

**Comment by f0rmatme** [comment]
^

**Comment by bigmemes420** [comment]
The one in clanmanmode however does not cause this bug and since that plugin already has the functionality, maybe just remove it from player indicators.
